/* Autonomous universal shop prototype. No fetch, XHR, beacons, forms to a server, or external assets. */
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7"/></svg>';
const heart='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20 6a5 5 0 0 0-7 0l-1 1-1-1a5 5 0 0 0-7 7l8 8 8-8a5 5 0 0 0 0-7Z"/></svg>';
const icons={
 tyres:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="60" cy="60" r="43"/><circle cx="60" cy="60" r="27"/><circle cx="60" cy="60" r="10"/><path d="M36 25l9 15m39-15-9 15M17 54l18 3m68-3-18 3M25 89l15-9m55 9-15-9M60 17v16m0 54v16"/></svg>',
 wheels:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="60" cy="60" r="43"/><circle cx="60" cy="60" r="31"/><circle cx="60" cy="60" r="8"/><path d="M60 29v23m0 16v23M29 60h23m16 0h23M38 38l16 16m12 12 16 16m0-44L66 54M54 66 38 82"/></svg>',
 oils:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M44 26h32v13l10 10v47H34V49l10-10V26Zm0 14h32M50 20h20v6M47 63h26M47 73h20M84 47h11v19H84"/></svg>',
 filters:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M31 35h58v50H31zM31 45h58M40 45v31m10-31v31m10-31v31m10-31v31m10-31v31M40 89h40"/></svg>',
 brakes:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="62" cy="60" r="34"/><circle cx="62" cy="60" r="11"/><path d="M28 42h20v36H28a36 36 0 0 1 0-36Zm55-16a39 39 0 0 1 13 68M54 27a35 35 0 0 1 23 0"/></svg>',
 batteries:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M24 42h72v48H24zM35 34h15v8m20-8h15v8M41 58v17m-8-9h16m26 0h16"/></svg>'
};
const taxonomy=[
 {id:'tyres-wheels',name:'Шины и диски',items:[['tyres','Шины'],['wheels','Диски']]},
 {id:'maintenance',name:'ТО и расходники',items:[['motor-oils','Моторные масла'],['transmission-oils','Трансмиссионные масла'],['fluids','Технические жидкости'],['oil-filters','Масляные фильтры'],['air-filters','Воздушные фильтры'],['cabin-filters','Салонные фильтры'],['fuel-filters','Топливные фильтры'],['spark-plugs','Свечи'],['belts','Ремни и ролики']]},
 {id:'braking',name:'Тормозная система',items:[['brake-pads','Колодки'],['brake-discs','Диски'],['brake-drums','Барабаны'],['calipers','Суппорты'],['brake-sensors','Датчики']]},
 {id:'suspension-steering',name:'Подвеска и рулевое',items:[['shocks','Амортизаторы'],['springs','Пружины'],['arms','Рычаги'],['ball-joints','Шаровые опоры'],['bushings','Сайлентблоки'],['hubs','Ступицы и подшипники'],['tie-rods','Рулевые тяги'],['tie-ends','Рулевые наконечники']]},
 {id:'engine',name:'Двигатель',items:[['gaskets','Прокладки'],['engine-mounts','Опоры двигателя'],['engine-sensors','Датчики'],['engine-pumps','Помпы и узлы']]},
 {id:'cooling',name:'Охлаждение и климат',items:[['radiators','Радиаторы'],['thermostats','Термостаты'],['coolant-pumps','Помпы'],['fans','Вентиляторы'],['air-conditioning','Кондиционирование']]},
 {id:'transmission',name:'Трансмиссия и сцепление',items:[['clutches','Комплекты сцепления'],['flywheels','Маховики'],['drives','Приводы'],['cv-joints','ШРУС'],['gearbox','Элементы КПП']]},
 {id:'electrics',name:'Электрика',items:[['batteries','Аккумуляторы'],['starters','Стартеры'],['alternators','Генераторы'],['electric-sensors','Датчики'],['bulbs','Лампы']]},
 {id:'exhaust',name:'Выхлопная система',items:[['mufflers','Глушители'],['exhaust-pipes','Трубы и соединения']]},
 {id:'body',name:'Кузов, свет и стекло',items:[['lights','Оптика'],['wipers','Щётки'],['body-parts','Кузовные элементы']]}
];
const categoryName=id=>taxonomy.find(g=>g.id===id)?.name||taxonomy.flatMap(g=>g.items).find(x=>x[0]===id)?.[1]||'Каталог товаров';
const groupFor=id=>taxonomy.find(g=>g.id===id||g.items.some(x=>x[0]===id));
const product=(id,group,sub,brand,name,article,variant,price,extra={})=>({id,group,sub,category:group,brand,name,article,variant,price,unit:'шт.',stock:'in',stockQty:12,delivery:'Самовывоз после подтверждения',fit:'check',popularity:50,...extra});
const products=[
 product('tyre-nord','tyres-wheels','tyres','Nordway','Iceform X5','TR-20555-16','205/55 R16 91T · зима · XL',8490,{season:'Зима',width:'205',profile:'55',diameter:'16',winterType:'Шипованная',runflat:'Нет',xl:'Да',fit:'match',popularity:99}),
 product('tyre-vector','tyres-wheels','tyres','Vector','CityTour Pro','TR-22550-17','225/50 R17 98W · лето · XL',11900,{season:'Лето',width:'225',profile:'50',diameter:'17',winterType:'—',runflat:'Нет',xl:'Да',popularity:86}),
 product('tyre-polar','tyres-wheels','tyres','Polar','Gripline 7','TR-21560-16','215/60 R16 99H · зима · RunFlat',10200,{season:'Зима',width:'215',profile:'60',diameter:'16',winterType:'Фрикционная',runflat:'Да',xl:'Нет',stock:'order',delivery:'DEMO поставка: 3–4 дня',popularity:79}),
 product('tyre-road','tyres-wheels','tyres','Nordway','Roadline 4','TR-19565-15','195/65 R15 · лето',6290,{season:'Лето',width:'195',profile:'65',diameter:'15',runflat:'Нет',xl:'Нет',fit:'match'}),
 product('wheel-arc','tyres-wheels','wheels','Arc','Диск Line 16','WH-16-ARC','R16 · 6.5J · 5×112',7290,{diameter:'16',width:'6.5J',pcd:'5×112',et:'45',dia:'57.1',wheelType:'Литой',color:'Серебристый',stock:'order',delivery:'DEMO поставка: 3 дня'}),
 product('wheel-forge','tyres-wheels','wheels','Vector','Диск Mesh 17','WH-17-MESH','R17 · 7J · 5×114.3',8990,{diameter:'17',width:'7J',pcd:'5×114.3',et:'40',dia:'67.1',wheelType:'Литой',color:'Графит'}),
 product('oil-atlas','maintenance','motor-oils','Atlas','Моторное масло 5W-30','OI-530-4L','5W-30 · 4 л · допуск уточняется',3890,{unit:'канистра',viscosity:'5W-30',oilType:'Синтетическое',volume:'4 л',specification:'Допуск требует проверки',fit:'match',popularity:95}),
 product('oil-mobil','maintenance','motor-oils','Mobil','Моторное масло 5W-40','OI-540-4L','5W-40 · 4 л',4590,{unit:'канистра',viscosity:'5W-40',oilType:'Синтетическое',volume:'4 л',specification:'Допуск требует проверки'}),
 product('oil-gear','maintenance','transmission-oils','Atlas','Трансмиссионное масло 75W-90','OI-7590-1L','75W-90 · 1 л',1690,{unit:'бутылка',viscosity:'75W-90',oilType:'Трансмиссионное',volume:'1 л',specification:'Подбор по агрегату'}),
 product('oil-fluid','maintenance','fluids','Atlas','Тормозная жидкость DOT 4','FL-DOT4-1L','DOT 4 · 1 л',990,{unit:'бутылка',viscosity:'DOT 4',oilType:'Тормозная жидкость',volume:'1 л',specification:'DOT 4'}),
 product('fluid-cool','maintenance','fluids','Coolant','Антифриз Longlife','FL-LL-5L','5 л · тип уточняется',1890,{unit:'канистра',volume:'5 л',oilType:'Охлаждающая жидкость',specification:'Тип требует проверки'}),
 product('filter-mann','maintenance','oil-filters','MANN-FILTER','Масляный фильтр W712/95','FI-W71295','Масляный · артикул DEMO',1190,{filterType:'Масляный',fit:'match',popularity:91}),
 product('filter-air','maintenance','air-filters','Airline','Воздушный фильтр A230','FI-A230','Воздушный · артикул DEMO',1450,{filterType:'Воздушный'}),
 product('filter-cabin','maintenance','cabin-filters','Airline','Салонный фильтр C410','FI-C410','Салонный · артикул DEMO',1390,{filterType:'Салонный',stock:'out',stockQty:0,delivery:'Срок не указан'}),
 product('filter-fuel','maintenance','fuel-filters','MANN-FILTER','Топливный фильтр F12','FI-F12','Топливный · артикул DEMO',1990,{filterType:'Топливный'}),
 product('spark-plug','maintenance','spark-plugs','NGK','Свеча зажигания P6','SP-P6','Свеча · 1 шт.',890,{partType:'Свечи'}),
 product('brake-ate','braking','brake-pads','ATE','Тормозные колодки Front','BR-FRONT-01','Передняя ось · комплект',4290,{unit:'комплект',partType:'Колодки',axle:'Передняя',fit:'match',popularity:89}),
 product('brake-pads-rear','braking','brake-pads','TRW','Тормозные колодки Rear','BR-REAR-02','Задняя ось · комплект',3990,{unit:'комплект',partType:'Колодки',axle:'Задняя'}),
 product('brake-disc','braking','brake-discs','ATE','Тормозной диск D280','BR-D280','Передняя ось · 280 мм',5190,{partType:'Диски',axle:'Передняя'}),
 product('brake-disc-rear','braking','brake-discs','TRW','Тормозной диск R260','BR-R260','Задняя ось · 260 мм',4690,{partType:'Диски',axle:'Задняя'}),
 product('battery-start','electrics','batteries','Start','Аккумулятор 60 А·ч','BA-60-540','60 А·ч · 540 А',7890,{capacity:'60 А·ч',cranking:'540 А',polarity:'Обратная',size:'242×175×190',technology:'EFB',stock:'order',delivery:'DEMO поставка: 2 дня'}),
 product('battery-plus','electrics','batteries','Start','Аккумулятор 70 А·ч','BA-70-650','70 А·ч · 650 А',8990,{capacity:'70 А·ч',cranking:'650 А',polarity:'Прямая',size:'278×175×190',technology:'AGM',stock:'out',stockQty:0,delivery:'Срок не указан'}),
 product('shock-front','suspension-steering','shocks','KYB','Амортизатор Front','SU-SH-FR','Передняя ось · левый',6390,{partType:'Амортизаторы',position:'Передняя левая'}),
 product('arm-left','suspension-steering','arms','Lemforder','Рычаг подвески L1','SU-ARM-L1','Передняя ось · левый',7590,{partType:'Рычаги',position:'Передняя левая'}),
 product('tie-rod','suspension-steering','tie-rods','TRW','Рулевая тяга T5','ST-T5','Передняя ось',3290,{partType:'Рулевые тяги',position:'Передняя'}),
 product('gasket','engine','gaskets','Elring','Прокладка крышки G4','EN-G4','Двигатель · артикул DEMO',1690,{partType:'Прокладки'}),
 product('engine-mount','engine','engine-mounts','Febi','Опора двигателя M2','EN-M2','Правая сторона',4890,{partType:'Опоры двигателя',position:'Правая'}),
 product('radiator','cooling','radiators','Nissens','Радиатор охлаждения R1','CO-R1','Система охлаждения',11900,{partType:'Радиаторы'}),
 product('clutch','transmission','clutches','Sachs','Комплект сцепления C1','TR-C1','Комплект · применимость уточняется',19900,{unit:'комплект',partType:'Сцепление'}),
 product('starter','electrics','starters','Bosch','Стартер S12','EL-S12','Электрика · 12 В',13900,{partType:'Стартеры'}),
 product('wiper','body','wipers','Bosch','Щётки Aero 600/450','BO-WIPER','Комплект · 600/450 мм',2590,{unit:'комплект',partType:'Щётки'})
];
const keyFor=p=>p.sub==='tyres'||p.sub==='wheels'?p.sub:p.group==='maintenance'?(p.sub.includes('filter')?'filters':'oils'):p.group==='braking'?'brakes':p.sub==='batteries'?'batteries':p.group;
for(const key of ['suspension-steering','engine','transmission','electrics','cooling','body','exhaust'])icons[key]=icons.brakes;
const byId=id=>products.find(p=>p.id===id);
const label=id=>categoryName(id);
const models={Volkswagen:['Polo','Golf'],Kia:['Rio','Ceed'],Toyota:['Corolla','Camry'],Hyundai:['Solaris','Creta']};
const savedCars=[{make:'Volkswagen',model:'Polo',year:'2020',engine:'1.6',customerId:'DEMO-CAR-1'},{make:'Kia',model:'Rio',year:'2021',engine:'1.6',customerId:'DEMO-CAR-2'}];
const demoCar={...savedCars[0],customerId:''};
const storage={cart:'kolesovik.shop.prototype.cart.v1',favorites:'kolesovik.shop.prototype.favorites.v1',vehicle:'kolesovik.shop.prototype.vehicle.v1'};
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function cleanCart(raw){const result={};if(!raw||typeof raw!=='object')return result;for(const [id,qty] of Object.entries(raw)){const p=byId(id);if(p&&p.stock!=='out'&&Number.isSafeInteger(qty)&&qty>=1&&qty<=99)result[id]=qty}return result}
function cleanVehicle(raw){return raw&&models[raw.make]?.includes(raw.model)?{make:raw.make,model:raw.model,year:raw.year||'',engine:raw.engine||'',customerId:raw.customerId||''}:null}
let cart=cleanCart(read(storage.cart,{}));
let favorites=new Set((Array.isArray(read(storage.favorites,[]))?read(storage.favorites,[]):[]).filter(id=>!!byId(id)));
let vehicle=cleanVehicle(read(storage.vehicle,null));
let state=new URLSearchParams(location.search).get('state')||(vehicle?'VEHICLE_SELECTED':'SHOP_HOME');
let category='all',query='',filters={},sort='popular',visibleCount=8,panel=null,detailId=null,detailQty=1,lastFocus=null,toastTimer=null,quantities={},vehicleMode='guest';
let selectSequence=0,openSelect=null,openMenu=null;
function shopSelect(id,label,items,value='',placeholder='Все',config={}){
 const menuId='shop-options-'+(++selectSequence),selected=items.find(([key])=>String(key)===String(value));
 const optionRows=[['',placeholder],...items].map(([key,text])=>'<button type="button" class="shop-select-option" role="option" data-action="select-option" tabindex="-1" data-value="'+esc(key)+'" aria-selected="'+(String(key)===String(value))+'">'+esc(text)+'</button>').join('');
 return '<div class="shop-field shop-select"'+(id?' id="'+id+'"':'')+' data-select-key="'+esc(config.key||id)+'"'+(config.filter?' data-filter="'+esc(config.filter)+'"':'')+' data-value="'+esc(value)+'"><span class="shop-field-label" id="'+menuId+'-label">'+esc(label)+'</span><button type="button" class="shop-select-trigger" data-action="select-toggle" aria-haspopup="listbox" aria-expanded="false" aria-controls="'+menuId+'" aria-labelledby="'+menuId+'-label '+menuId+'-value" '+(config.disabled?'disabled':'')+'><span id="'+menuId+'-value">'+esc(selected?.[1]||placeholder)+'</span><span aria-hidden="true">⌄</span></button>'+(config.name?'<input type="hidden" name="'+esc(config.name)+'" value="'+esc(value)+'">':'')+'<div class="shop-select-menu" id="'+menuId+'" role="listbox" aria-labelledby="'+menuId+'-label" hidden>'+optionRows+'</div></div>';
}
function closeShopSelect(restore=false){if(!openSelect)return;const trigger=$('.shop-select-trigger',openSelect),root=openSelect,menu=openMenu;if(trigger&&menu){trigger.setAttribute('aria-expanded','false');menu.hidden=true;menu.removeAttribute('style');root.append(menu);if(restore)trigger.focus({preventScroll:true})}openSelect=null;openMenu=null}
function positionShopMenu(){
 if(!openSelect||!openMenu)return;
 const trigger=$('.shop-select-trigger',openSelect),drawer=openSelect.closest('.shop-drawer'),menu=openMenu;
 if(!trigger?.isConnected){closeShopSelect();return}
 const anchor=trigger.getBoundingClientRect(),bounds=drawer?drawer.getBoundingClientRect():{top:0,left:0,right:innerWidth,bottom:innerHeight};
 const topLimit=drawer?Math.max(bounds.top+8,$('.overlay-head',drawer).getBoundingClientRect().bottom+8):8;
 const footer=drawer?$('.drawer-footer',drawer):null;
 const bottomLimit=Math.min(bounds.bottom-8,footer?.getBoundingClientRect().top-8||innerHeight-8,innerHeight-8);
 if(anchor.bottom<topLimit||anchor.top>bottomLimit){closeShopSelect();return}
 const below=bottomLimit-anchor.bottom-4,above=anchor.top-topLimit-4;
 const flip=below<Math.min(220,menu.scrollHeight)&&above>below;
 const available=Math.max(44,flip?above:below),height=Math.min(220,menu.scrollHeight,available);
 const width=Math.min(anchor.width,bounds.right-bounds.left-16),left=Math.max(bounds.left+8,Math.min(anchor.left,bounds.right-width-8));
 const top=flip?anchor.top-4-height:anchor.bottom+4;
 menu.style.position=drawer?'absolute':'fixed';menu.style.left=(left-(drawer?bounds.left:0))+'px';menu.style.top=(top-(drawer?bounds.top:0))+'px';
 menu.style.width=width+'px';menu.style.maxHeight=height+'px';
}
function openShopMenu(root,focus='selected'){
 if(!root||$('.shop-select-trigger',root).disabled)return;
 closeShopSelect();openSelect=root;
 const trigger=$('.shop-select-trigger',root),menu=$('.shop-select-menu',root),drawer=root.closest('.shop-drawer');
 openMenu=menu;(drawer||document.body).append(menu);menu.hidden=false;trigger.setAttribute('aria-expanded','true');positionShopMenu();
 if(!openMenu)return;
 const options=[...menu.querySelectorAll('[role=option]')];const target=focus==='last'?options.at(-1):focus==='first'?options[0]:options.find(x=>x.getAttribute('aria-selected')==='true')||options[0];
 target?.focus({preventScroll:true});if(target)menu.scrollTop=Math.max(0,target.offsetTop-menu.clientHeight/2);
}
function setShopOptions(root,items,value='',placeholder='Все',disabled=false){const menu=$('.shop-select-menu',root),trigger=$('.shop-select-trigger',root);menu.innerHTML=[['',placeholder],...items].map(([key,text])=>'<button type="button" class="shop-select-option" role="option" data-action="select-option" tabindex="-1" data-value="'+esc(key)+'" aria-selected="'+(String(key)===String(value))+'">'+esc(text)+'</button>').join('');root.dataset.value=value;trigger.querySelector('span').textContent=items.find(([key])=>String(key)===String(value))?.[1]||placeholder;trigger.disabled=disabled;const hidden=$('input[type=hidden]',root);if(hidden)hidden.value=value}
function chooseShopOption(option){const root=openSelect,value=option.dataset.value;root.dataset.value=value;$('.shop-select-trigger span',root).textContent=option.textContent;const hidden=$('input[type=hidden]',root);if(hidden)hidden.value=value;openMenu.querySelectorAll('[role=option]').forEach(x=>x.setAttribute('aria-selected',String(x===option)));closeShopSelect(true);root.dispatchEvent(new CustomEvent('shop-select-change',{bubbles:true,detail:{key:root.dataset.selectKey,value}}))}
const scenarios=['SHOP_HOME','VEHICLE_SELECTED','KNOWN_CUSTOMER','CATEGORY','SEARCH_RESULTS','CART_WITH_ITEMS','CART_EMPTY'];
if(!scenarios.includes(state))state='SHOP_HOME';
function setScenario(next,initial=false){state=next;filters={};sort='popular';visibleCount=8;query='';category='all';panel=null;detailId=null;
 if(next==='SHOP_HOME'){vehicle=null;save(storage.vehicle,vehicle)}
 if(next==='VEHICLE_SELECTED'){vehicle={...demoCar};save(storage.vehicle,vehicle)}
 if(next==='KNOWN_CUSTOMER'){vehicle=null;vehicleMode='known';save(storage.vehicle,null)}
 if(next==='CATEGORY')category='tyres';
 if(next==='SEARCH_RESULTS')query='фильтр';
 if(next==='CART_WITH_ITEMS'){cart={'tyre-nord':4,'oil-atlas':1,'filter-mann':1};save(storage.cart,cart);panel='cart'}
 if(next==='CART_EMPTY'){cart={};save(storage.cart,cart);panel='cart'}
 if(!initial)history.replaceState(null,'','?state='+next);
 render();if(panel)renderPanel();
}
function fitText(p){return !vehicle?'Совместимость не проверена':p.fit==='match'?'Подходит выбранному автомобилю · DEMO':'Совместимость нужно уточнить · DEMO'}
function stockText(p){return p.stock==='in'?'В наличии · DEMO':p.stock==='order'?'Под заказ · DEMO':'Нет в наличии · DEMO'}
function quantity(){return Object.values(cart).reduce((a,b)=>a+b,0)}
function total(){return Object.entries(cart).reduce((a,[id,q])=>a+(byId(id)?.price||0)*q,0)}
function statusToast(message){const el=$('#shop-toast');el.innerHTML=esc(message)+' <button type="button" data-action="cart">Перейти в корзину</button>';el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},5000)}
function brand(){return '<a class="brand" href="#top" data-action="home" aria-label="КОЛЕСОВИК — магазин"><span class="brand-symbol">К</span><span>КОЛЕСОВИК</span></a>'}
function header(){return '<header id="top" class="next-header next-container">'+brand()+'<nav id="site-nav" class="next-nav" aria-label="Главная навигация"><button type="button" data-action="catalog">Каталог</button><a href="#catalog" data-category="tyres">Шины</a><a href="#catalog" data-category="motor-oils">Масла</a><a href="#service-link">Услуги</a></nav><div class="shop-header-actions"><button type="button" class="header-icon" data-action="favorites" aria-label="Избранное">'+heart+'<span class="header-word">Избранное</span></button><button type="button" class="header-icon cart-trigger" data-action="cart" aria-label="Корзина, '+quantity()+' товаров"><span class="cart-symbol" aria-hidden="true">▣</span><span class="header-word">Корзина</span><span class="cart-badge" aria-hidden="true">'+quantity()+'</span></button><button type="button" class="next-menu" data-action="menu" aria-label="Открыть меню" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div></header>'}
function breadcrumbs(){return '<nav class="breadcrumbs next-container" aria-label="Путь"><a href="#top" data-action="home">Главная</a><span> / </span><button type="button" data-action="all">Магазин</button>'+(category==='all'?'':'<span> / </span><span aria-current="page">'+esc(categoryName(category))+'</span>')+'</nav>'}
function intro(){return '<section class="shop-intro next-container" aria-labelledby="page-title"><div class="eyebrow">КОЛЕСОВИК · АВТОТОВАРЫ</div><div class="shop-intro-row"><div><h1 id="page-title">Магазин автотоваров</h1><p>Шины, диски, масла, расходники и запчасти для обслуживания и ремонта автомобиля.</p></div><span class="shop-edition">DEMO КАТАЛОГ</span></div><form id="shop-search" class="shop-search" role="search"><label for="search-input">Поиск по каталогу'+(category==='all'?'':' · '+esc(categoryName(category)))+'</label><div><input id="search-input" name="search" type="search" placeholder="Название, бренд, артикул..." value="'+esc(query)+'" autocomplete="off"><button type="submit" class="button primary">Найти '+arrow+'</button></div></form></section>'}
function vehicleBlock(){return '<section class="shop-entry next-container" aria-label="Каталог и автомобиль"><button type="button" class="catalog-trigger" data-action="catalog"><span aria-hidden="true">☰</span><strong>Каталог</strong>'+arrow+'</button><div class="vehicle-context"><div><div class="eyebrow">ВАШ АВТОМОБИЛЬ</div><strong id="vehicle-title">'+(vehicle?esc(vehicle.make+' '+vehicle.model):state==='KNOWN_CUSTOMER'?'Выберите автомобиль':'Автомобиль не выбран')+'</strong><small>'+(vehicle?esc([vehicle.year,vehicle.engine].filter(Boolean).join(' · '))+' · DEMO':'Поиск и заказ доступны без выбора')+'</small></div><button type="button" class="text-link" data-action="vehicle">'+(vehicle?'Изменить':'Выбрать')+'</button></div></section>'}
function categoryBlock(){return '<div class="quick-access next-container" aria-label="Популярные категории">'+[['tyres','Шины'],['motor-oils','Масла'],['oil-filters','Фильтры'],['brake-pads','Тормоза']].map(([id,name])=>'<button type="button" data-action="category" data-category="'+id+'">'+name+'</button>').join('')+'</div>'}
function vehicleShelf(){if(!vehicle)return '';const ids=['oil-atlas','filter-mann','brake-ate','tyre-nord'];return '<section class="shelf next-section next-container" aria-labelledby="shelf-title"><div class="section-line"><div><div class="eyebrow">ПОДБОР ПО АВТОМОБИЛЮ · DEMO</div><h2 id="shelf-title">Для вашего автомобиля</h2><p>'+esc(vehicle.make+' '+vehicle.model)+' · примеры из разных категорий. Применимость требует проверки.</p></div></div><div class="shelf-grid">'+ids.map(id=>{const p=byId(id);return '<button type="button" class="shelf-item" data-action="details" data-id="'+id+'"><span>'+icons[keyFor(p)]+'</span><small>'+esc(categoryName(p.sub))+'</small><strong>'+esc(p.brand+' '+p.name)+'</strong></button>'}).join('')+'</div></section>'}
const fieldLabels={brand:'Производитель',season:'Сезон',width:'Ширина',profile:'Профиль',diameter:'Диаметр',winterType:'Тип зимней шины',runflat:'RunFlat',xl:'XL',pcd:'PCD',et:'ET',dia:'DIA',wheelType:'Материал / тип',color:'Цвет',viscosity:'Вязкость',oilType:'Тип масла / жидкости',volume:'Объём',specification:'Допуск / спецификация',filterType:'Тип фильтра',partType:'Тип детали',axle:'Ось',position:'Сторона / положение',capacity:'Ёмкость',cranking:'Пусковой ток',polarity:'Полярность',size:'Размер',technology:'Технология'};
const categoryFields={tyres:['brand','season','width','profile','diameter','winterType','runflat','xl'],wheels:['brand','diameter','width','pcd','et','dia','wheelType','color'],oils:['brand','viscosity','oilType','volume','specification'],filters:['brand','filterType'],brakes:['partType','brand','axle'],suspension:['partType','brand','position'],batteries:['brand','capacity','cranking','polarity','size','technology'],generic:['partType','brand','position']};
function filterProfile(){const group=groupFor(category)?.id||category;return category==='tyres'?'tyres':category==='wheels'?'wheels':category==='batteries'?'batteries':group==='maintenance'?(category.includes('filter')?'filters':'oils'):group==='braking'?'brakes':group==='suspension-steering'?'suspension':'generic'}
function inCategory(p){return category==='all'||p.group===category||p.sub===category}
function optionsFor(key){return [...new Set(products.filter(inCategory).map(p=>p[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ru'))}
function filterCount(){return Object.entries(filters).filter(([,v])=>v!==''&&v!==false&&v!=null).length}
function filterFields(){
 const fields=category==='all'?['brand']:(categoryFields[filterProfile()]||categoryFields.generic);
 const select=key=>shopSelect('',fieldLabels[key],optionsFor(key).map(v=>[v,key==='diameter'?'R'+v:v]),filters[key]||'','Все',{key:'filter:'+key,filter:key});
 return '<details open><summary>Производитель</summary>'+select('brand')+'</details>'+
 '<details open><summary>Цена</summary><div class="price-range"><label>От, ₽<input type="number" min="0" inputmode="numeric" data-filter="minPrice" value="'+esc(filters.minPrice||'')+'" placeholder="От"></label><label>До, ₽<input type="number" min="0" inputmode="numeric" data-filter="maxPrice" value="'+esc(filters.maxPrice||'')+'" placeholder="До"></label></div></details>'+
 '<details open><summary>Наличие и получение</summary>'+
 shopSelect('','Наличие',[['in','В наличии'],['order','Под заказ'],['out','Нет в наличии']],filters.stock||'','Любое',{key:'filter:stock',filter:'stock'})+
 shopSelect('','Срок получения',[['pickup','После подтверждения'],['order','Под заказ']],filters.deliveryType||'','Любой',{key:'filter:deliveryType',filter:'deliveryType'})+'</details>'+
 '<details open><summary>Совместимость</summary><label class="filter-checkbox"><input type="checkbox" data-filter="vehicleOnly" '+(filters.vehicleOnly?'checked':'')+' '+(vehicle?'':'disabled')+'> Только для моего автомобиля'+(vehicle?'':' · выберите авто')+'</label></details>'+
 (category==='all'?'':'<details><summary>Параметры категории</summary>'+fields.filter(x=>x!=='brand').map(select).join('')+'</details>');
}
function filtered(){const term=query.trim().toLocaleLowerCase('ru');const items=products.filter(p=>inCategory(p)&&(!term||[p.name,p.brand,p.article,p.variant,categoryName(p.group),categoryName(p.sub)].some(v=>String(v).toLocaleLowerCase('ru').includes(term)))&&Object.entries(filters).every(([k,v])=>{
  if(!v)return true;if(k==='minPrice')return p.price>=Number(v);if(k==='maxPrice')return p.price<=Number(v);if(k==='stock')return p.stock===v;if(k==='deliveryType')return v==='order'?p.stock==='order':p.stock==='in';if(k==='vehicleOnly')return !!vehicle&&p.fit==='match';return String(p[k]||'')===v}));
 return items.sort((a,b)=>sort==='cheap'?a.price-b.price:sort==='expensive'?b.price-a.price:b.popularity-a.popularity)}
function chips(){const labels={minPrice:'От',maxPrice:'До',stock:'Наличие',deliveryType:'Получение',vehicleOnly:'Для автомобиля'};return Object.entries(filters).filter(([,v])=>v).map(([k,v])=>'<button type="button" class="filter-chip" data-action="remove-filter" data-key="'+k+'">'+esc(labels[k]||fieldLabels[k]||k)+' '+esc(k==='vehicleOnly'?'':k==='minPrice'||k==='maxPrice'?money(v):v)+' <span aria-hidden="true">×</span></button>').join('')}
function qFor(p){return quantities[p.id]||(p.sub==='tyres'?4:1)}
function productCard(p){const q=qFor(p),kind=keyFor(p);return '<article class="next-product-card" data-product="'+p.id+'"><div class="next-product-media">'+icons[kind]+'<span>'+esc(categoryName(p.sub))+' · DEMO</span><button type="button" class="next-favorite'+(favorites.has(p.id)?' is-favorite':'')+'" data-action="favorite" data-id="'+p.id+'" aria-label="'+(favorites.has(p.id)?'Убрать из избранного':'В избранное')+': '+esc(p.name)+'" aria-pressed="'+favorites.has(p.id)+'">'+heart+'</button></div><div class="next-product-identity"><span class="next-product-brand">'+esc(p.brand)+'</span><h3>'+esc(p.name)+'</h3><p class="next-product-size">'+esc(p.variant)+'</p><div class="next-product-tags"><span>'+esc(p.article)+'</span>'+(vehicle?'<span>'+fitText(p)+'</span>':'')+'</div></div><div class="next-product-price"><strong>'+money(p.price)+'</strong><small>за 1 '+esc(p.unit)+' · DEMO PRICE</small><span class="next-product-total" data-product-total="'+p.id+'">'+q+' '+esc(p.unit)+' · '+money(q*p.price)+'</span></div><div class="next-product-availability"><span class="next-product-status next-product-status--'+(p.stock==='in'?'available':p.stock==='order'?'delivery':'unavailable')+'">'+stockText(p)+'</span><span class="next-product-delivery">'+esc(p.delivery)+'</span></div><div class="next-product-action-row"><div class="next-quantity" role="group" aria-label="Количество '+esc(p.name)+'"><button type="button" data-action="card-minus" data-id="'+p.id+'" aria-label="Уменьшить количество '+esc(p.name)+'" '+(q<=1?'disabled':'')+'>−</button><output>'+q+'</output><button type="button" data-action="card-plus" data-id="'+p.id+'" aria-label="Увеличить количество '+esc(p.name)+'" '+(q>=99?'disabled':'')+'>+</button></div><button type="button" class="next-product-details" data-action="details" data-id="'+p.id+'">Подробнее</button></div><button type="button" class="next-product-buy" data-action="add" data-id="'+p.id+'" '+(p.stock==='out'?'disabled':'')+'>'+(p.stock==='out'?'Нет в наличии':cart[p.id]?'В корзине · добавить ещё':'В корзину')+'</button></article>'}
function catalog(){const items=filtered(),active=filterCount(),shown=items.slice(0,visibleCount);return '<section id="catalog" class="next-section next-container" aria-labelledby="catalog-title"><div class="section-line"><div><div class="eyebrow">АССОРТИМЕНТ</div><h2 id="catalog-title">'+(query?'Результаты поиска':categoryName(category))+'</h2><p>'+(query?'«'+esc(query)+'» · ':'')+(category==='all'?'':esc(categoryName(category))+' · ')+'Найдено: '+items.length+'</p></div></div><div class="catalog-toolbar"><button type="button" class="button secondary mobile-filter" data-action="filters">Фильтры'+(active?' · '+active:'')+'</button>'+shopSelect('sort-select','Сортировка',[['popular','По популярности'],['cheap','Сначала дешевле'],['expensive','Сначала дороже']],sort,'По популярности',{key:'sort'})+'</div>'+(active?'<div class="active-filters">'+chips()+'<button type="button" class="text-link" data-action="reset-filters">Очистить</button></div>':'')+'<div class="catalog-layout"><aside class="catalog-filters" aria-label="Фильтры категории"><div class="filter-heading"><strong>Фильтры</strong>'+(active?'<button type="button" class="text-link" data-action="reset-filters">Очистить</button>':'')+'</div><div class="filter-fields">'+filterFields()+'</div></aside><div class="catalog-main">'+(items.length?'<div class="shop-grid">'+shown.map(productCard).join('')+'</div>':'<div class="empty-rule">По этим параметрам ничего не найдено. Измените запрос или очистите фильтры.</div>')+(items.length>shown.length?'<button type="button" class="button secondary load-more" data-action="more">Показать ещё</button>':'')+'</div></div></section>'}
function serviceLink(){return '<section id="service-link" class="service-cross next-container"><div><div class="eyebrow">ТОВАРЫ И СЕРВИС</div><h2>Запчасти можно установить у нас</h2><p>Подберём детали и выполним работы в сервисе на Станционной 11/1.</p></div><div class="service-actions"><button type="button" class="button primary" data-action="service">Записаться в сервис</button><button type="button" class="text-link" data-action="ask">Задать вопрос '+arrow+'</button></div></section>'}
function footer(){return '<footer class="next-footer next-container">'+brand()+'<span>Сервис, которому можно доверить дорогу.</span><button type="button" class="next-footer-login" data-action="cart">Корзина · '+quantity()+'</button><small>© 2026 КОЛЕСОВИК · Дизайн-прототип магазина</small></footer>'}
function render(){document.title='Магазин автотоваров — КОЛЕСОВИК · визуальный прототип';$('#state-select').value=state;$('#technical-key').textContent=state;const y=window.scrollY;$('#app').innerHTML='<div class="next-home">'+header()+'<main id="content">'+breadcrumbs()+intro()+vehicleBlock()+categoryBlock()+vehicleShelf()+catalog()+serviceLink()+'</main>'+footer()+'</div>';window.scrollTo(0,y)}
// The shell remains mounted. Changing a vehicle make only updates model options.
function overlay(title,body,type){closeShopSelect();const root=$('#overlay-root');if(!root.firstElementChild){lastFocus=document.activeElement;root.innerHTML='<div class="overlay-backdrop"><section class="overlay-panel shop-drawer" role="dialog" aria-modal="true" aria-labelledby="overlay-title" tabindex="-1"><div class="overlay-head"><div><div class="eyebrow">КОЛЕСОВИК · АВТОТОВАРЫ</div><h2 id="overlay-title"></h2></div><button type="button" data-action="close" aria-label="Закрыть">×</button></div><div class="overlay-content"></div></section></div>';document.body.classList.add('overlay-open');$('.shop-drawer').focus()}
 panel=type;$('.shop-drawer').classList.toggle('filter-drawer',type==='filters');$('#overlay-title').textContent=title;$('.overlay-content').innerHTML=body}
function close(){closeShopSelect();panel=null;detailId=null;$('#overlay-root').innerHTML='';document.body.classList.remove('overlay-open');(lastFocus?.isConnected?lastFocus:$('.cart-trigger'))?.focus()}
function cartBody(){if(!Object.keys(cart).length)return '<div class="drawer-scroll cart-empty"><div class="empty-mark">▣</div><h3>Корзина пока пуста</h3><p>Выберите товары в каталоге — автомобиль указывать необязательно.</p><button type="button" class="button primary" data-action="close">Перейти к товарам</button></div>';return '<div class="drawer-scroll"><p class="drawer-note">Демонстрационные товары и цены. Наличие уточняется перед оформлением.</p><ul class="cart-list">'+Object.entries(cart).map(([id,q])=>{const p=byId(id);return '<li class="cart-item" data-cart-id="'+id+'"><div class="cart-item-media">'+icons[keyFor(p)]+'</div><div class="cart-item-copy"><small>'+esc(categoryName(p.sub))+' · DEMO</small><h3>'+esc(p.brand+' '+p.name)+'</h3><p>'+esc(p.variant)+'</p>'+(vehicle?'<span class="cart-fit">'+fitText(p)+'</span>':'')+'<div class="cart-item-price">'+money(p.price)+' за 1 '+esc(p.unit)+'</div><div class="cart-item-bottom"><div class="cart-stepper" role="group" aria-label="Количество '+esc(p.name)+'"><button type="button" data-action="minus" data-id="'+id+'" aria-label="Уменьшить количество '+esc(p.name)+'" '+(q===1?'disabled':'')+'>−</button><output>'+q+'</output><button type="button" data-action="plus" data-id="'+id+'" aria-label="Увеличить количество '+esc(p.name)+'">+</button></div><strong>'+money(p.price*q)+'</strong></div><button type="button" class="remove-item" data-action="remove" data-id="'+id+'">Убрать</button></div></li>'}).join('')+'</ul></div><div class="drawer-footer"><div class="cart-totals"><div><span>Товары · '+quantity()+' шт.</span><strong>'+money(total())+'</strong></div><div class="cart-grand"><span>Итого · DEMO</span><strong>'+money(total())+'</strong></div></div><button type="button" class="button primary large" data-action="checkout">Перейти к оформлению '+arrow+'</button></div>'}
function detailSpecs(p){const keys=['diameter','width','profile','season','winterType','runflat','xl','pcd','et','dia','wheelType','color','viscosity','oilType','volume','specification','filterType','partType','axle','position','capacity','cranking','polarity','size','technology'];return '<dl class="detail-specs"><div><dt>Артикул</dt><dd>'+esc(p.article)+'</dd></div>'+keys.filter(k=>p[k]).map(k=>'<div><dt>'+esc(fieldLabels[k])+'</dt><dd>'+esc(k==='diameter'?'R'+p[k]:p[k])+'</dd></div>').join('')+'<div><dt>Наличие</dt><dd>'+stockText(p)+'</dd></div><div><dt>Получение</dt><dd>'+esc(p.delivery)+'</dd></div><div><dt>Совместимость</dt><dd>'+fitText(p)+'</dd></div></dl>'}
function renderPanel(){if(panel==='cart')overlay('Корзина',cartBody(),'cart');
 else if(panel==='catalog')overlay('Каталог','<div class="drawer-scroll catalog-tree"><button type="button" class="catalog-all" data-action="category" data-category="all">Весь каталог '+arrow+'</button>'+taxonomy.map(g=>'<section><h3>'+esc(g.name)+'</h3><div>'+g.items.map(([id,name])=>'<button type="button" data-action="category" data-category="'+id+'">'+esc(name)+' '+arrow+'</button>').join('')+'</div></section>').join('')+'</div>','catalog');
 else if(panel==='favorites')overlay('Избранное','<div class="drawer-scroll"><p class="drawer-note">Сохранено только в этом браузере.</p>'+(favorites.size?'<div class="favorite-list">'+[...favorites].map(id=>{const p=byId(id);return '<div><span class="mini-icon">'+icons[keyFor(p)]+'</span><div><small>'+esc(categoryName(p.sub))+'</small><strong>'+esc(p.brand+' '+p.name)+'</strong><p>'+money(p.price)+' · DEMO</p></div><button type="button" class="button secondary" data-action="details" data-id="'+id+'">Подробнее</button></div>'}).join('')+'</div>':'<p class="empty-rule">В избранном пока нет товаров.</p>')+'</div>','favorites');
 else if(panel==='details'&&detailId){const p=byId(detailId);overlay('О товаре','<div class="drawer-scroll"><div class="detail-media">'+icons[keyFor(p)]+'</div><div class="eyebrow">'+esc(categoryName(p.sub))+' · DEMO</div><h3>'+esc(p.brand+' '+p.name)+'</h3><p>'+esc(p.variant)+'</p>'+(vehicle?'<p class="detail-vehicle">'+esc(vehicle.make+' '+vehicle.model)+' · '+fitText(p)+'</p>':'')+detailSpecs(p)+'</div><div class="drawer-footer detail-footer"><div class="detail-price"><span>Цена за 1 '+esc(p.unit)+'</span><strong>'+money(p.price)+'</strong></div><div class="detail-quantity"><span>Количество</span><div class="next-quantity" role="group" aria-label="Количество товара"><button type="button" data-action="detail-minus" aria-label="Уменьшить количество" '+(detailQty<=1||p.stock==='out'?'disabled':'')+'>−</button><output id="detail-qty">'+detailQty+'</output><button type="button" data-action="detail-plus" aria-label="Увеличить количество" '+(detailQty>=Math.min(99,p.stockQty||99)||p.stock==='out'?'disabled':'')+'>+</button></div></div><div class="detail-total"><span>Итого</span><strong id="detail-total">'+money(detailQty*p.price)+'</strong></div><button type="button" class="button primary large" data-action="add" data-id="'+p.id+'" '+(p.stock==='out'?'disabled':'')+'>'+(p.stock==='out'?'Нет в наличии':'В корзину')+'</button></div>','details')}
 else if(panel==='filters')overlay('Фильтры · '+categoryName(category),'<div class="drawer-scroll"><div class="filter-fields">'+filterFields()+'</div></div><div class="drawer-footer filter-footer"><button type="button" class="button secondary" data-action="reset-filters">Очистить</button><button type="button" class="button primary" data-action="close">Показать '+filtered().length+' товаров</button></div>','filters');
 else if(panel==='vehicle')vehiclePanel();
 else if(panel==='checkout')checkoutPanel();
 else if(panel==='success')successPanel();
 else if(panel==='service')overlay('Запись в сервис','<div class="drawer-scroll"><p>Запись в сервис недоступна в этой демонстрации.</p></div>','service');
 else if(panel==='ask')overlay('Задать вопрос','<div class="drawer-scroll"><p>Чат недоступен в этой демонстрации.</p></div>','ask')}
function vehiclePanel(){
 const v=vehicle||{make:'',model:'',year:'',engine:''};
 if(vehicleMode==='known')return overlay('Выберите автомобиль','<div class="drawer-scroll"><p>Сохранённые автомобили · DEMO.</p><div class="saved-cars">'+savedCars.map((c,i)=>'<button type="button" data-action="known-car" data-index="'+i+'"><strong>'+esc(c.make+' '+c.model)+'</strong><span>'+c.year+' · '+c.engine+' · DEMO</span>'+arrow+'</button>').join('')+'</div><button type="button" class="text-link" data-action="guest-vehicle">Другой автомобиль '+arrow+'</button></div>','vehicle');
 overlay('Ваш автомобиль','<div class="drawer-scroll"><p>Выберите марку и модель. Для точной совместимости детали позже могут понадобиться год, двигатель или VIN.</p><form id="vehicle-form" class="shop-form">'+
 shopSelect('vehicle-make','Марка',Object.keys(models).map(x=>[x,x]),v.make,'Выберите марку',{name:'make',key:'vehicle-make'})+
 shopSelect('vehicle-model','Модель',(models[v.make]||[]).map(x=>[x,x]),v.model,'Выберите модель',{name:'model',key:'vehicle-model',disabled:!v.make})+
 '<details class="vehicle-more"><summary>Уточнить год и двигатель · необязательно</summary>'+
 shopSelect('vehicle-year','Год',['2018','2019','2020','2021','2022','2023'].map(x=>[x,x]),v.year,'Не указан',{name:'year',key:'vehicle-year'})+
 shopSelect('vehicle-engine','Двигатель',['1.4','1.6','2.0'].map(x=>[x,x]),v.engine,'Не указан',{name:'engine',key:'vehicle-engine'})+
 '</details><button type="submit" class="button primary large">Сохранить автомобиль</button></form></div>','vehicle');
}
function checkoutPanel(){overlay('Оформление · DEMO','<div class="drawer-scroll"><p class="drawer-note">Это демонстрация оформления. Заказ не будет отправлен.</p><form id="checkout-form" class="shop-form"><label>Имя<input name="name" autocomplete="name" required placeholder="Ваше имя"></label><label>Телефон<input name="phone" type="tel" inputmode="tel" autocomplete="tel" required placeholder="+7 999 000-00-00" pattern="[+0-9 ()-]{10,22}"></label><div class="pickup-box"><div class="eyebrow">ПОЛУЧЕНИЕ</div><strong>Самовывоз из КОЛЕСОВИКа</strong><p>Подольск · Станционная 11/1</p></div><label>Комментарий <span>необязательно</span><textarea name="comment" rows="3" placeholder="Что уточнить перед получением"></textarea></label><label class="consent"><input type="checkbox" name="consent" required><span>Понимаю, что это демонстрация и заказ не будет отправлен.</span></label><button type="submit" class="button primary large">Оформить заказ</button><p class="form-note">Оплата в демонстрации недоступна.</p></form></div>','checkout')}
function successPanel(){overlay('Результат оформления · DEMO','<div class="drawer-scroll success-screen"><div class="success-mark">✓</div><h3>Пример подтверждения</h3><strong>№ DEMO-001</strong><p>Товары и самовывоз показаны на примере.</p><p class="overlay-note">Заказ не отправлен. Контактные данные не сохранялись и не передавались.</p><button type="button" class="button primary" data-action="close">Вернуться в магазин</button></div>','success')}

function add(id,q){const p=byId(id);if(!p||p.stock==='out')return;cart[id]=Math.min(99,(cart[id]||0)+q);save(storage.cart,cart);if(panel==='details')close();render();statusToast('Добавлено в корзину')}
function adjust(id,delta){if(!cart[id])return;cart[id]=Math.max(1,Math.min(99,cart[id]+delta));save(storage.cart,cart);render();renderPanel()}
function navigateCategory(id){category=id;filters={};visibleCount=8;state='CATEGORY';history.replaceState(null,'','?state=CATEGORY');if(panel)close();render();$('#catalog').scrollIntoView({block:'start',behavior:'smooth'})}
function showControls(open){$('#prototype-controls').hidden=!open;$('#controls-open').setAttribute('aria-expanded',String(open));if(open){lastFocus=document.activeElement;$('.controls-panel').focus()}else if(lastFocus?.isConnected)lastFocus.focus()}
document.addEventListener('submit',e=>{if(e.target.id==='shop-search'){e.preventDefault();query=String(new FormData(e.target).get('search')||'').trim();filters={};visibleCount=8;state='SEARCH_RESULTS';history.replaceState(null,'','?state=SEARCH_RESULTS');render();$('#catalog').scrollIntoView({block:'start',behavior:'smooth'})}
 else if(e.target.id==='vehicle-form'){e.preventDefault();const d=new FormData(e.target),v=cleanVehicle({make:String(d.get('make')),model:String(d.get('model')),year:String(d.get('year')),engine:String(d.get('engine'))});if(!v)return;vehicle=v;save(storage.vehicle,v);state='VEHICLE_SELECTED';history.replaceState(null,'','?state=VEHICLE_SELECTED');close();render();$('#shelf-title').scrollIntoView({block:'start',behavior:'smooth'})}
 else if(e.target.id==='checkout-form'){e.preventDefault();if(!e.target.reportValidity())return;panel='success';renderPanel()}});
document.addEventListener('shop-select-change',e=>{
 const {key,value}=e.detail;
 if(key==='vehicle-make'){setShopOptions($('#vehicle-model'),(models[value]||[]).map(x=>[x,x]),'','Выберите модель',!value);return}
 if(key==='sort'){sort=value;render();$('.catalog-toolbar .shop-select-trigger')?.focus();return}
 if(key.startsWith('filter:')){filters[key.slice(7)]=value;visibleCount=8;const inDrawer=panel==='filters';render();if(inDrawer){const show=$('.filter-footer [data-action=close]');if(show)show.textContent='Показать '+filtered().length+' товаров'}else $('.catalog-filters [data-filter="'+key.slice(7)+'"] .shop-select-trigger')?.focus()}
});
document.addEventListener('change',e=>{
 if(e.target.matches('input[data-filter]')){const k=e.target.dataset.filter;filters[k]=e.target.type==='checkbox'?e.target.checked:e.target.value;visibleCount=8;const inDrawer=panel==='filters';render();if(inDrawer){const show=$('.filter-footer [data-action=close]');if(show)show.textContent='Показать '+filtered().length+' товаров'}return}
 if(e.target.id==='theme-select'){const value=e.target.value;save('shop-prototype-theme',value);document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value}
});
document.addEventListener('click',e=>{if(openSelect&&!openSelect.contains(e.target)&&!openMenu?.contains(e.target))closeShopSelect();if(e.target.classList?.contains('overlay-backdrop')){close();return}const link=e.target.closest('a[data-category]');if(link){e.preventDefault();navigateCategory(link.dataset.category);return}const t=e.target.closest('[data-action]');if(!t)return;const action=t.dataset.action,id=t.dataset.id;
 if(action==='select-toggle'){const root=t.closest('.shop-select');openSelect===root?closeShopSelect(true):openShopMenu(root);return}
 if(action==='select-option'){chooseShopOption(t);return}
 if(action==='menu'){const nav=$('#site-nav');nav.classList.toggle('open');t.setAttribute('aria-expanded',String(nav.classList.contains('open')))}
 else if(action==='home'||action==='all'){e.preventDefault();category='all';query='';filters={};visibleCount=8;state='SHOP_HOME';history.replaceState(null,'','?state=SHOP_HOME');if(panel)close();render();window.scrollTo({top:0,behavior:'smooth'})}
 else if(action==='category')navigateCategory(t.dataset.category)
 else if(action==='favorite'){favorites.has(id)?favorites.delete(id):favorites.add(id);save(storage.favorites,[...favorites]);render();if(panel==='favorites')renderPanel()}
 else if(action==='details'){detailId=id;detailQty=qFor(byId(id));panel='details';renderPanel()}
 else if(action==='add'){const q=panel==='details'?detailQty:qFor(byId(id));add(id,Number(q)||1)}
 else if(['cart','favorites','catalog','filters','service','ask'].includes(action)){panel=action;renderPanel()}
 else if(action==='vehicle'){vehicleMode=state==='KNOWN_CUSTOMER'||!!vehicle?.customerId?'known':'guest';panel='vehicle';renderPanel()}
 else if(action==='guest-vehicle'){vehicleMode='guest';renderPanel()}
 else if(action==='known-car'){vehicle={...savedCars[Number(t.dataset.index)]};save(storage.vehicle,vehicle);state='VEHICLE_SELECTED';history.replaceState(null,'','?state=VEHICLE_SELECTED');close();render()}
 else if(action==='close')close()
 else if(action==='minus'||action==='plus')adjust(id,action==='minus'?-1:1)
 else if(action==='card-minus'||action==='card-plus'){const p=byId(id);quantities[id]=Math.max(1,Math.min(99,(quantities[id]||qFor(p))+(action==='card-plus'?1:-1)));const card=t.closest('.next-product-card');card.querySelector('.next-quantity output').textContent=quantities[id];card.querySelector('[data-product-total]').textContent=quantities[id]+' '+p.unit+' · '+money(quantities[id]*p.price);card.querySelector('[data-action=card-minus]').disabled=quantities[id]===1}
 else if(action==='detail-minus'||action==='detail-plus'){const p=byId(detailId);detailQty=Math.max(1,Math.min(99,p.stockQty||99,detailQty+(action==='detail-plus'?1:-1)));$('#detail-qty').textContent=detailQty;$('#detail-total').textContent=money(detailQty*p.price);$('[data-action=detail-minus]').disabled=detailQty<=1;$('[data-action=detail-plus]').disabled=detailQty>=Math.min(99,p.stockQty||99)}
 else if(action==='remove'){delete cart[id];save(storage.cart,cart);render();renderPanel()}
 else if(action==='checkout'){panel='checkout';renderPanel()}
 else if(action==='reset-filters'){filters={};visibleCount=8;render();if(panel==='filters')renderPanel()}
 else if(action==='remove-filter'){delete filters[t.dataset.key];render()}
 else if(action==='more'){visibleCount+=8;render()}});
document.addEventListener('scroll',e=>{if(openSelect&&e.target!==openMenu)positionShopMenu()},{capture:true,passive:true});
window.addEventListener('resize',positionShopMenu,{passive:true});
document.addEventListener('keydown',e=>{
 const root=e.target.closest('.shop-select')||(openMenu?.contains(e.target)?openSelect:null);
 if(root){
   const options=[...(openSelect===root?openMenu:$('.shop-select-menu',root)).querySelectorAll('[role=option]')],index=options.indexOf(e.target);
  if(e.key==='Escape'&&openSelect===root){e.preventDefault();closeShopSelect(true);return}
  if(e.key==='Tab'&&openSelect===root){closeShopSelect();return}
  if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(openSelect!==root){openShopMenu(root,e.key==='ArrowDown'?'first':'last')}else options[(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length]?.focus();return}
  if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role=option]')){e.preventDefault();chooseShopOption(e.target);return}
  if((e.key==='Enter'||e.key===' ')&&e.target.matches('.shop-select-trigger')){e.preventDefault();openSelect===root?closeShopSelect(true):openShopMenu(root);return}
 }
  if(e.key==='Escape'){if(openSelect){closeShopSelect(true);return}if(panel)close();else showControls(false)}
  if(e.key==='Tab'&&panel){const drawer=$('.shop-drawer'),focusable=[...drawer.querySelectorAll('a[href],button:not(:disabled),input:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(x=>x.getClientRects().length&&!x.hidden);if(focusable.length){const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
});
$('#controls-open').addEventListener('click',()=>showControls(true));$('#controls-close').addEventListener('click',()=>showControls(false));$('#controls-hide').addEventListener('click',()=>showControls(false));
$('#state-select').addEventListener('change',e=>{showControls(false);setScenario(e.target.value)});
setScenario(state,true);
