/* Autonomous universal shop prototype. No fetch, XHR, beacons, forms to a server, or external assets. */
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7"/></svg>';
const heart='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20 6a5 5 0 0 0-7 0l-1 1-1-1a5 5 0 0 0-7 7l8 8 8-8a5 5 0 0 0 0-7Z"/></svg>';
const icons={
 tyres:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="60" cy="60" r="43"/><circle cx="60" cy="60" r="27"/><circle cx="60" cy="60" r="10"/><path d="M36 25l9 15m39-15-9 15M17 54l18 3m68-3-18 3M25 89l15-9m55 9-15-9M60 17v16m0 54v16"/></svg>',
 wheels:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="60" cy="60" r="43"/><circle cx="60" cy="60" r="31"/><circle cx="60" cy="60" r="8"/><path d="M60 29v23m0 16v23M29 60h23m16 0h23M38 38l16 16m12 12 16 16m0-44L66 54M54 66 38 82"/></svg>',
 oils:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M44 26h32v13l10 10v47H34V49l10-10V26Zm0 14h32M50 20h20v6M47 63h26M47 73h20M84 47h11v19H84"/></svg>',
 filters:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M31 35h58v50H31zM31 45h58M40 45v31m10-31v31m10-31v31m10-31v31m10-31v31M40 89h40"/></svg>',
 brakes:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="62" cy="60" r="34"/><circle cx="62" cy="60" r="11"/><path d="M28 42h20v36H28a36 36 0 0 1 0-36Zm55-16a39 39 0 0 1 13 68M54 27a35 35 0 0 1 23 0"/></svg>',
 batteries:'<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M24 42h72v48H24zM35 34h15v8m20-8h15v8M41 58v17m-8-9h16m26 0h16"/></svg>'
};
const categories=[['all','Все товары'],['tyres','Шины'],['wheels','Диски'],['oils','Масла и жидкости'],['filters','Фильтры'],['brakes','Тормоза'],['batteries','Аккумуляторы']];
const products=[
 {id:'tyre-nord',category:'tyres',brand:'Nordway',name:'Iceform X5',article:'TR-20555-16',variant:'205/55 R16 91T · зима · XL',price:8490,unit:'шт.',stock:'in',stockQty:14,delivery:'Самовывоз после подтверждения',fit:'match',season:'Зима',width:'205',profile:'55',diameter:'16',specs:['205/55 R16 91T','Зимняя','XL','RunFlat: нет']},
 {id:'tyre-vector',category:'tyres',brand:'Vector',name:'CityTour Pro',article:'TR-22550-17',variant:'225/50 R17 98W · лето · XL',price:11900,unit:'шт.',stock:'in',stockQty:8,delivery:'Самовывоз после подтверждения',fit:'check',season:'Лето',width:'225',profile:'50',diameter:'17',specs:['225/50 R17 98W','Летняя','XL','RunFlat: нет']},
 {id:'tyre-polar',category:'tyres',brand:'Polar',name:'Gripline 7',article:'TR-21560-16',variant:'215/60 R16 99H · зима · RunFlat',price:10200,unit:'шт.',stock:'order',stockQty:12,delivery:'DEMO поставка: 3–4 дня',fit:'check',season:'Зима',width:'215',profile:'60',diameter:'16',specs:['215/60 R16 99H','Зимняя','RunFlat','XL: нет']},
 {id:'wheel-arc',category:'wheels',brand:'Arc',name:'Диск Line 16',article:'WH-16-ARC',variant:'R16 · 6.5J · серебристый',price:7290,unit:'шт.',stock:'order',stockQty:8,delivery:'DEMO поставка: 3 дня',fit:'check',diameter:'16',finish:'Серебристый',specs:['R16','6.5J','Серебристый']},
 {id:'oil-atlas',category:'oils',brand:'Atlas',name:'Моторное масло 5W-30',article:'OI-530-4L',variant:'5W-30 · 4 л · допуск уточняется',price:3890,unit:'канистра',stock:'in',stockQty:10,delivery:'Самовывоз после подтверждения',fit:'match',viscosity:'5W-30',volume:'4 л',specs:['5W-30','4 л','Допуск требует проверки']},
 {id:'oil-fluid',category:'oils',brand:'Atlas',name:'Тормозная жидкость DOT 4',article:'FL-DOT4-1L',variant:'DOT 4 · 1 л',price:990,unit:'бутылка',stock:'in',stockQty:10,delivery:'Самовывоз после подтверждения',fit:'check',viscosity:'DOT 4',volume:'1 л',specs:['DOT 4','1 л']},
 {id:'filter-mann',category:'filters',brand:'MANN-FILTER',name:'Масляный фильтр W712/95',article:'FI-W71295',variant:'Масляный · артикул DEMO',price:1190,unit:'шт.',stock:'in',stockQty:9,delivery:'Самовывоз после подтверждения',fit:'match',filterType:'Масляный',specs:['Масляный фильтр','Артикул DEMO']},
 {id:'filter-air',category:'filters',brand:'Airline',name:'Воздушный фильтр A230',article:'FI-A230',variant:'Воздушный · артикул DEMO',price:1450,unit:'шт.',stock:'in',stockQty:9,delivery:'Самовывоз после подтверждения',fit:'check',filterType:'Воздушный',specs:['Воздушный фильтр','Артикул DEMO']},
 {id:'filter-cabin',category:'filters',brand:'Airline',name:'Салонный фильтр C410',article:'FI-C410',variant:'Салонный · артикул DEMO',price:1390,unit:'шт.',stock:'out',stockQty:0,delivery:'Срок не указан',fit:'check',filterType:'Салонный',specs:['Салонный фильтр','Артикул DEMO']},
 {id:'brake-ate',category:'brakes',brand:'Ate',name:'Тормозные колодки Front',article:'BR-FRONT-01',variant:'Передняя ось · комплект',price:4290,unit:'комплект',stock:'in',stockQty:6,delivery:'Самовывоз после подтверждения',fit:'match',axle:'Передняя',specs:['Передняя ось','Комплект','Применимость требует проверки']},
 {id:'battery-start',category:'batteries',brand:'Start',name:'Аккумулятор 60 А·ч',article:'BA-60-540',variant:'60 А·ч · 540 А',price:7890,unit:'шт.',stock:'order',stockQty:4,delivery:'DEMO поставка: 2 дня',fit:'check',capacity:'60 А·ч',specs:['60 А·ч','540 А','Полярность требует проверки']},
 {id:'battery-plus',category:'batteries',brand:'Start',name:'Аккумулятор 70 А·ч',article:'BA-70-650',variant:'70 А·ч · 650 А',price:8990,unit:'шт.',stock:'out',stockQty:0,delivery:'Срок не указан',fit:'check',capacity:'70 А·ч',specs:['70 А·ч','650 А','Полярность требует проверки']}
];
const byId=id=>products.find(p=>p.id===id);
const label=category=>categories.find(x=>x[0]===category)?.[1]||'Товары';
const models={Volkswagen:['Polo','Golf'],Kia:['Rio','Ceed'],Toyota:['Corolla','Camry']};
const demoCar={make:'Volkswagen',model:'Polo',year:'2020',engine:'1.6'};
const storage={cart:'kolesovik.shop.prototype.cart.v1',favorites:'kolesovik.shop.prototype.favorites.v1',vehicle:'kolesovik.shop.prototype.vehicle.v1'};
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function cleanCart(raw){const result={};if(!raw||typeof raw!=='object')return result;for(const [id,qty] of Object.entries(raw)){const p=byId(id);if(p&&p.stock!=='out'&&Number.isSafeInteger(qty)&&qty>=1&&qty<=99)result[id]=qty}return result}
function cleanVehicle(raw){return raw&&models[raw.make]?.includes(raw.model)&&/^20\d\d$/.test(raw.year)&&['1.4','1.6','2.0'].includes(raw.engine)?raw:null}
let cart=cleanCart(read(storage.cart,{}));
let favorites=new Set((Array.isArray(read(storage.favorites,[]))?read(storage.favorites,[]):[]).filter(id=>!!byId(id)));
let vehicle=cleanVehicle(read(storage.vehicle,null));
let state=new URLSearchParams(location.search).get('state')||(vehicle?'VEHICLE_SELECTED':'SHOP_HOME');
let category='all',query='',filters={},visibleCount=8,panel=null,detailId=null,detailQty=1,lastFocus=null,toastTimer=null;
const scenarios=['SHOP_HOME','VEHICLE_SELECTED','CATEGORY','SEARCH_RESULTS','CART_WITH_ITEMS','CART_EMPTY'];
if(!scenarios.includes(state))state='SHOP_HOME';
function setScenario(next,initial=false){state=next;filters={};visibleCount=8;query='';category='all';panel=null;detailId=null;
 if(next==='SHOP_HOME'){vehicle=null;save(storage.vehicle,vehicle)}
 if(next==='VEHICLE_SELECTED'){if(!initial||!vehicle)vehicle={...demoCar};save(storage.vehicle,vehicle)}
 if(next==='CATEGORY')category='tyres';
 if(next==='SEARCH_RESULTS')query='фильтр';
 if(next==='CART_WITH_ITEMS'){if(!initial||!Object.keys(cart).length){cart={'tyre-nord':4,'oil-atlas':1,'filter-mann':1};save(storage.cart,cart)}panel='cart'}
 if(next==='CART_EMPTY'){cart={};save(storage.cart,cart);panel='cart'}
 if(!initial)history.replaceState(null,'','?state='+next);
 render();
}
function categoryName(p){return label(p.category)}
function fitText(p){return !vehicle?'Автомобиль не выбран':p.fit==='match'?'Подходит вашему автомобилю · DEMO':'Совместимость требует проверки · DEMO'}
function stockText(p){return p.stock==='in'?'В наличии · DEMO':p.stock==='order'?'Под заказ · DEMO':'Нет в наличии · DEMO'}
function quantity(){return Object.values(cart).reduce((a,b)=>a+b,0)}
function total(){return Object.entries(cart).reduce((a,[id,q])=>a+(byId(id)?.price||0)*q,0)}
function statusToast(message){const el=$('#shop-toast');el.innerHTML=esc(message)+' <button type="button" data-action="cart">Перейти в корзину</button>';el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},5000)}
function brand(){return '<a class="brand" href="#top" data-action="home" aria-label="КОЛЕСОВИК — магазин"><span class="brand-symbol">К</span><span>КОЛЕСОВИК</span></a>'}
function header(){return '<header id="top" class="next-header next-container">'+brand()+'<nav id="site-nav" class="next-nav" aria-label="Главная навигация"><a href="#categories">Категории</a><a href="#catalog" data-category="tyres">Шины</a><a href="#catalog" data-category="oils">Масла</a><a href="#catalog" data-category="filters">Фильтры</a><a href="#service-link">Услуги</a></nav><div class="shop-header-actions"><button type="button" class="header-icon" data-action="favorites" aria-label="Избранное">'+heart+'<span class="header-word">Избранное</span></button><button type="button" class="header-icon cart-trigger" data-action="cart" aria-label="Корзина, '+quantity()+' товаров"><span class="cart-symbol" aria-hidden="true">▣</span><span class="header-word">Корзина</span><span class="cart-badge" aria-hidden="true">'+quantity()+'</span></button><button type="button" class="next-menu" data-action="menu" aria-label="Открыть меню" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div></header>'}
function breadcrumbs(){return '<nav class="breadcrumbs next-container" aria-label="Путь"><a href="#top">Главная</a><span> / </span><span aria-current="page">Магазин</span></nav>'}
function intro(){return '<section class="shop-intro next-container" aria-labelledby="page-title"><div class="eyebrow">КОЛЕСОВИК · МАГАЗИН ДЛЯ АВТОМОБИЛЯ</div><div class="shop-intro-row"><div><h1 id="page-title">Магазин</h1><p>Шины, масла, фильтры и другие товары для автомобиля.</p></div><span class="shop-edition">DEMO КАТАЛОГ</span></div><form id="shop-search" class="shop-search" role="search"><label for="search-input">Поиск по каталогу</label><div><input id="search-input" name="search" type="search" placeholder="Название, бренд, артикул..." value="'+esc(query)+'" autocomplete="off"><button type="submit" class="button primary">Найти '+arrow+'</button></div></form></section>'}
function vehicleBlock(){return '<section class="vehicle-context next-container" aria-labelledby="vehicle-title"><div class="vehicle-icon" aria-hidden="true">⌖</div><div><div class="eyebrow">ВАШ АВТОМОБИЛЬ</div><h2 id="vehicle-title">'+(vehicle?esc(vehicle.make+' '+vehicle.model):'Выберите автомобиль')+'</h2><p>'+(vehicle?esc(vehicle.year+' · '+vehicle.engine)+' · DEMO контекст':'Чтобы видеть товары в контексте вашего автомобиля. Поиск и корзина доступны без выбора.')+'</p></div><button type="button" class="button secondary" data-action="vehicle">'+(vehicle?'Изменить':'Выбрать автомобиль')+'</button></section>'}
function categoryBlock(){return '<section id="categories" class="next-section next-container" aria-labelledby="categories-title"><div class="section-line"><div><div class="eyebrow">НАЙДИТЕ НУЖНОЕ</div><h2 id="categories-title">Категории</h2></div></div><div class="shop-categories">'+categories.filter(x=>x[0]!=='all').map(x=>'<button type="button" class="shop-category'+(category===x[0]?' active':'')+'" data-action="category" data-category="'+x[0]+'"><span class="category-icon">'+icons[x[0]]+'</span><span>'+x[1]+'</span>'+arrow+'</button>').join('')+'</div></section>'}
function vehicleShelf(){if(!vehicle)return '';const ids=['oil-atlas','filter-mann','brake-ate','tyre-nord'];return '<section class="shelf next-section next-container" aria-labelledby="shelf-title"><div class="section-line"><div><div class="eyebrow">DEMO ПОДБОР · СОВМЕСТИМОСТЬ НЕ ПОДТВЕРЖДЕНА</div><h2 id="shelf-title">Для вашего автомобиля</h2><p>'+esc(vehicle.make+' '+vehicle.model)+' · товары из разных категорий. Реальную применимость нужно проверить.</p></div></div><div class="shelf-grid">'+ids.map(id=>{const p=byId(id);return '<button type="button" class="shelf-item" data-action="details" data-id="'+id+'"><span>'+icons[p.category]+'</span><small>'+categoryName(p)+'</small><strong>'+p.brand+' '+p.name+'</strong><em>'+arrow+'</em></button>'}).join('')+'</div></section>'}
const filterSpec={tyres:[['brand','Бренд'],['season','Сезон'],['width','Ширина'],['profile','Профиль'],['diameter','Диаметр']],oils:[['brand','Бренд'],['viscosity','Вязкость / тип'],['volume','Объём']],filters:[['brand','Бренд'],['filterType','Тип']],wheels:[['brand','Бренд'],['diameter','Диаметр'],['finish','Цвет']],brakes:[['brand','Бренд'],['axle','Ось']],batteries:[['brand','Бренд'],['capacity','Ёмкость']],all:[['category','Категория'],['brand','Бренд']]};
function optionsFor(key){const pool=category==='all'?products:products.filter(p=>p.category===category);return [...new Set(pool.map(p=>key==='category'?p.category:p[key]).filter(Boolean))]}
function filterFields(){return (filterSpec[category]||filterSpec.all).map(([key,title])=>'<label>'+title+'<select data-filter="'+key+'"><option value="">Все</option>'+optionsFor(key).map(v=>'<option value="'+esc(v)+'"'+(filters[key]===v?' selected':'')+'>'+esc(key==='category'?label(v):key==='diameter'?'R'+v:v)+'</option>').join('')+'</select></label>').join('')}
function filtered(){const term=query.trim().toLocaleLowerCase('ru');return products.filter(p=>(category==='all'||p.category===category)&&(!term||[p.name,p.brand,p.article,categoryName(p),p.variant].some(v=>v.toLocaleLowerCase('ru').includes(term)))&&Object.entries(filters).every(([k,v])=>!v||(k==='category'?p.category:p[k])===v))}
function productCard(p){const added=!!cart[p.id];const defaultQty=p.category==='tyres'?4:1;const max=Math.min(12,p.stockQty||1);return '<article class="next-product-card shop-card" data-product="'+p.id+'"><div class="next-product-media shop-product-media"><span>'+categoryName(p)+' · DEMO</span>'+icons[p.category]+'<button type="button" class="next-favorite'+(favorites.has(p.id)?' is-favorite':'')+'" data-action="favorite" data-id="'+p.id+'" aria-label="'+(favorites.has(p.id)?'Убрать из избранного':'В избранное')+': '+esc(p.name)+'" aria-pressed="'+favorites.has(p.id)+'">'+heart+'</button></div><div class="next-product-identity"><span class="next-product-brand">'+esc(p.brand)+'</span><h3>'+esc(p.name)+'</h3><p class="next-product-size">'+esc(p.variant)+'</p></div><div class="shop-fit">'+fitText(p)+'</div><div class="next-product-price"><strong>'+money(p.price)+'</strong><small>за 1 '+esc(p.unit)+' · DEMO PRICE</small></div><div class="next-product-availability"><span>'+stockText(p)+'</span><small>'+esc(p.delivery)+'</small></div><div class="card-actions"><label>Кол-во<select class="card-qty" aria-label="Количество '+esc(p.name)+'" '+(p.stock==='out'?'disabled':'')+'>'+Array.from({length:max},(_,i)=>'<option value="'+(i+1)+'"'+(i+1===Math.min(defaultQty,max)?' selected':'')+'>'+(i+1)+'</option>').join('')+'</select></label><button type="button" class="button secondary" data-action="details" data-id="'+p.id+'">Подробнее</button></div><button type="button" class="next-product-buy" data-action="add" data-id="'+p.id+'" '+(p.stock==='out'?'disabled':'')+'>'+(p.stock==='out'?'Нет в наличии':added?'В корзине · добавить ещё':'В корзину')+'</button></article>'}
function catalog(){const items=filtered(),active=Object.values(filters).filter(Boolean).length,shown=items.slice(0,visibleCount);return '<section id="catalog" class="next-section next-container" aria-labelledby="catalog-title"><div class="section-line"><div><div class="eyebrow">СИНТЕТИЧЕСКИЕ ТОВАРЫ · DEMO PRICE</div><h2 id="catalog-title">'+(query?'Результаты поиска':category==='all'?'Каталог товаров':label(category))+'</h2><p>'+(query?'Запрос: «'+esc(query)+'». ':'')+'Найдено: '+items.length+'</p></div><button type="button" class="text-link" data-action="all">Все товары '+arrow+'</button></div><div class="catalog-layout"><aside class="catalog-filters" aria-label="Фильтры категории"><div class="filter-heading"><strong>Фильтры</strong><button type="button" data-action="reset-filters">Сбросить</button></div><div class="filter-fields">'+filterFields()+'</div></aside><div class="catalog-main"><button type="button" class="button secondary mobile-filter" data-action="filters">Фильтры'+(active?' · '+active:'')+'</button>'+(items.length?'<div class="shop-grid">'+shown.map(productCard).join('')+'</div>':'<div class="empty-rule">По этим параметрам ничего не найдено. Попробуйте другой запрос или сбросьте фильтры.</div>')+(items.length>shown.length?'<button type="button" class="button secondary load-more" data-action="more">Показать ещё</button>':'')+'</div></div></section>'}
function serviceLink(){return '<section id="service-link" class="service-cross next-container"><div><div class="eyebrow">ТОВАРЫ И СЕРВИС</div><h2>Понадобится установка?</h2><p>Шины связаны с шиномонтажом, расходники — с плановым ТО. Услуга не добавляется в корзину автоматически.</p></div><div><span>Шины → Шиномонтаж</span><span>Масло и фильтр → Плановое ТО</span></div></section>'}
function footer(){return '<footer class="next-footer next-container">'+brand()+'<span>Сервис, которому можно доверить дорогу.</span><button type="button" class="next-footer-login" data-action="cart">Корзина · '+quantity()+'</button><small>© 2026 КОЛЕСОВИК · Дизайн-прототип магазина</small></footer>'}
function render(){document.title='Магазин — КОЛЕСОВИК · визуальный прототип';$('#state-select').value=state;$('#technical-key').textContent=state;const y=window.scrollY;$('#app').innerHTML='<div class="next-home">'+header()+'<main id="content">'+breadcrumbs()+intro()+vehicleBlock()+categoryBlock()+vehicleShelf()+catalog()+serviceLink()+'</main>'+footer()+'</div>';renderPanel();window.scrollTo(0,y)}
function overlay(title,body,type){if(!$('#overlay-root').firstElementChild)lastFocus=document.activeElement;panel=type;$('#overlay-root').innerHTML='<div class="overlay-backdrop"><section class="overlay-panel shop-drawer '+(type==='filters'?'filter-drawer':'')+'" role="dialog" aria-modal="true" aria-labelledby="overlay-title" tabindex="-1"><div class="overlay-head"><div><div class="eyebrow">КОЛЕСОВИК · МАГАЗИН</div><h2 id="overlay-title">'+title+'</h2></div><button type="button" data-action="close" aria-label="Закрыть">×</button></div>'+body+'</section></div>';document.body.classList.add('overlay-open');$('.shop-drawer').focus()}
function close(){panel=null;detailId=null;$('#overlay-root').innerHTML='';document.body.classList.remove('overlay-open');(lastFocus?.isConnected?lastFocus:$('.cart-trigger'))?.focus()}
function cartBody(){if(!Object.keys(cart).length)return '<div class="drawer-scroll cart-empty"><div class="empty-mark">▣</div><h3>Корзина пока пуста</h3><p>Выберите товары в каталоге — автомобиль указывать необязательно.</p><button type="button" class="button primary" data-action="close">Перейти к товарам</button></div>';return '<div class="drawer-scroll"><p class="drawer-note">Синтетические товары и цены для проверки интерфейса. Наличие подтвердят перед реальным заказом.</p><ul class="cart-list">'+Object.entries(cart).map(([id,q])=>{const p=byId(id);return '<li class="cart-item" data-cart-id="'+id+'"><div class="cart-item-media">'+icons[p.category]+'</div><div class="cart-item-copy"><small>'+categoryName(p)+' · DEMO</small><h3>'+esc(p.brand+' '+p.name)+'</h3><p>'+esc(p.variant)+'</p><span class="cart-fit">'+fitText(p)+'</span><div class="cart-item-price">'+money(p.price)+' за 1 '+esc(p.unit)+'</div><div class="cart-item-bottom"><div class="cart-stepper" role="group" aria-label="Количество '+esc(p.name)+'"><button type="button" data-action="minus" data-id="'+id+'" aria-label="Уменьшить количество '+esc(p.name)+'" '+(q===1?'disabled':'')+'>−</button><output>'+q+'</output><button type="button" data-action="plus" data-id="'+id+'" aria-label="Увеличить количество '+esc(p.name)+'">+</button></div><strong>'+money(p.price*q)+'</strong></div><button type="button" class="remove-item" data-action="remove" data-id="'+id+'">Убрать</button></div></li>'}).join('')+'</ul></div><div class="drawer-footer"><div class="cart-totals"><div><span>Товары · '+quantity()+' шт.</span><strong>'+money(total())+'</strong></div><div class="cart-grand"><span>Итого · DEMO</span><strong>'+money(total())+'</strong></div></div><button type="button" class="button primary large" data-action="checkout">Перейти к оформлению '+arrow+'</button></div>'}
function renderPanel(){if(panel==='cart')overlay('Корзина',cartBody(),'cart');else if(panel==='favorites')overlay('Избранное','<div class="drawer-scroll"><p class="drawer-note">Сохранено только в этом браузере.</p>'+(favorites.size?'<div class="favorite-list">'+[...favorites].map(id=>{const p=byId(id);return '<div><span class="mini-icon">'+icons[p.category]+'</span><div><small>'+categoryName(p)+'</small><strong>'+esc(p.brand+' '+p.name)+'</strong><p>'+money(p.price)+' · DEMO</p></div><button type="button" class="button secondary" data-action="details" data-id="'+id+'">Подробнее</button></div>'}).join('')+'</div>':'<p class="empty-rule">В избранном пока нет товаров.</p>')+'</div>','favorites');else if(panel==='details'&&detailId){const p=byId(detailId);overlay('О товаре','<div class="drawer-scroll"><div class="detail-media">'+icons[p.category]+'</div><div class="eyebrow">'+categoryName(p)+' · DEMO</div><h3>'+esc(p.brand+' '+p.name)+'</h3><p>'+esc(p.variant)+'</p><dl class="detail-specs">'+p.specs.map(s=>'<div><dt>Характеристика</dt><dd>'+esc(s)+'</dd></div>').join('')+'<div><dt>Артикул</dt><dd>'+esc(p.article)+'</dd></div><div><dt>Наличие</dt><dd>'+stockText(p)+'</dd></div><div><dt>Получение</dt><dd>'+esc(p.delivery)+'</dd></div><div><dt>Совместимость</dt><dd>'+fitText(p)+'</dd></div></dl></div><div class="drawer-footer"><div class="detail-price"><strong>'+money(p.price)+'</strong><span>за 1 '+esc(p.unit)+' · DEMO PRICE</span></div><label>Количество<select id="detail-qty" '+(p.stock==='out'?'disabled':'')+'>'+Array.from({length:Math.min(12,p.stockQty||1)},(_,i)=>'<option value="'+(i+1)+'"'+(i+1===Math.min(detailQty,12,p.stockQty||1)?' selected':'')+'>'+(i+1)+'</option>').join('')+'</select></label><button type="button" class="button primary large" data-action="add" data-id="'+p.id+'" '+(p.stock==='out'?'disabled':'')+'>'+(p.stock==='out'?'Нет в наличии':'В корзину')+'</button></div>','details')}else if(panel==='filters')overlay('Фильтры · '+label(category),'<div class="drawer-scroll"><div class="filter-fields">'+filterFields()+'</div><button type="button" class="text-link" data-action="reset-filters">Сбросить фильтры</button></div><div class="drawer-footer"><button type="button" class="button primary large" data-action="close">Показать товары</button></div>','filters');else if(panel==='vehicle')vehiclePanel();else if(panel==='checkout')checkoutPanel();else if(panel==='success')successPanel()}
function vehiclePanel(){const v=vehicle||{make:'',model:'',year:'',engine:''};const opts=(values,current,empty)=>'<option value="">'+empty+'</option>'+values.map(x=>'<option value="'+esc(x)+'"'+(x===current?' selected':'')+'>'+esc(x)+'</option>').join('');overlay('Ваш автомобиль','<div class="drawer-scroll"><p>Выбор помогает показать DEMO контекст. Точную совместимость товаров нужно подтвердить отдельно.</p><form id="vehicle-form" class="shop-form"><label>Марка<select name="make" id="vehicle-make" required>'+opts(Object.keys(models),v.make,'Выберите марку')+'</select></label><label>Модель<select name="model" id="vehicle-model" required '+(v.make?'':'disabled')+'>'+opts(models[v.make]||[],v.model,'Выберите модель')+'</select></label><label>Год<select name="year" required>'+opts(['2018','2019','2020','2021','2022','2023'],v.year,'Выберите год')+'</select></label><label>Двигатель<select name="engine" required>'+opts(['1.4','1.6','2.0'],v.engine,'Выберите двигатель')+'</select></label><button type="submit" class="button primary large">Сохранить автомобиль</button></form></div>','vehicle')}
function checkoutPanel(){overlay('Оформление · DEMO','<div class="drawer-scroll"><p class="drawer-note">Это локальный пример оформления. Данные не отправляются, заказ не создаётся.</p><form id="checkout-form" class="shop-form"><label>Имя<input name="name" autocomplete="name" required placeholder="Ваше имя"></label><label>Телефон<input name="phone" type="tel" inputmode="tel" autocomplete="tel" required placeholder="+7 999 000-00-00" pattern="[+0-9 ()-]{10,22}"></label><div class="pickup-box"><div class="eyebrow">ПОЛУЧЕНИЕ</div><strong>Самовывоз из КОЛЕСОВИКа</strong><p>Подольск · Станционная 11/1</p></div><label>Комментарий <span>необязательно</span><textarea name="comment" rows="3" placeholder="Что уточнить перед получением"></textarea></label><label class="consent"><input type="checkbox" name="consent" required><span>Согласен на обработку персональных данных в сценарии прототипа. Ничего не отправляется.</span></label><button type="submit" class="button primary large">Оформить заказ</button><p class="form-note">Демонстрация: нажатие не создаёт заказ и не выполняет оплату.</p></form></div>','checkout')}
function successPanel(){overlay('Заказ принят · DEMO','<div class="drawer-scroll success-screen"><div class="success-mark">✓</div><h3>Заказ принят</h3><strong>№ DEMO-001</strong><p>Мы подтвердим наличие и свяжемся с вами — так будет выглядеть будущий экран.</p><p class="overlay-note">Заказ не отправлен — это демонстрация интерфейса. Контактные данные не сохранялись и не передавались.</p><button type="button" class="button primary" data-action="close">Вернуться в магазин</button></div>','success')}
function add(id,q){const p=byId(id);if(!p||p.stock==='out')return;cart[id]=Math.min(99,(cart[id]||0)+q);save(storage.cart,cart);const wasDetail=panel==='details';if(wasDetail)close();render();statusToast('Добавлено в корзину');}
function adjust(id,delta){if(!cart[id])return;cart[id]=Math.max(1,Math.min(99,cart[id]+delta));save(storage.cart,cart);render()}
function showControls(open){$('#prototype-controls').hidden=!open;$('#controls-open').setAttribute('aria-expanded',String(open));if(open){lastFocus=document.activeElement;$('.controls-panel').focus()}else if(lastFocus?.isConnected)lastFocus.focus()}
document.addEventListener('submit',e=>{if(e.target.id==='shop-search'){e.preventDefault();query=String(new FormData(e.target).get('search')||'').trim();category='all';filters={};visibleCount=8;state='SEARCH_RESULTS';history.replaceState(null,'','?state=SEARCH_RESULTS');render();$('#catalog').scrollIntoView({block:'start',behavior:'smooth'})}
 else if(e.target.id==='vehicle-form'){e.preventDefault();const d=new FormData(e.target),v={make:String(d.get('make')),model:String(d.get('model')),year:String(d.get('year')),engine:String(d.get('engine'))};if(!cleanVehicle(v))return;vehicle=v;save(storage.vehicle,vehicle);state='VEHICLE_SELECTED';history.replaceState(null,'','?state=VEHICLE_SELECTED');close();render();$('#shelf-title').scrollIntoView({block:'start',behavior:'smooth'})}
 else if(e.target.id==='checkout-form'){e.preventDefault();if(!e.target.reportValidity())return;panel='success';renderPanel()}});
document.addEventListener('change',e=>{if(e.target.id==='vehicle-make'){const sel=$('#vehicle-model');if(sel){sel.innerHTML='<option value="">Выберите модель</option>'+(models[e.target.value]||[]).map(x=>'<option value="'+x+'">'+x+'</option>').join('');sel.disabled=!e.target.value}}
 else if(e.target.matches('[data-filter]')){filters[e.target.dataset.filter]=e.target.value;visibleCount=8;const inDrawer=panel==='filters';render();if(inDrawer)panel='filters',renderPanel()}
 else if(e.target.id==='theme-select'){const value=e.target.value;try{localStorage.setItem('shop-prototype-theme',value)}catch{}document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value}});
document.addEventListener('click',e=>{if(e.target.classList?.contains('overlay-backdrop')){close();return}const link=e.target.closest('[data-category]');if(link&&link.tagName==='A'){e.preventDefault();category=link.dataset.category;query='';filters={};visibleCount=8;state='CATEGORY';history.replaceState(null,'','?state=CATEGORY');render();$('#catalog').scrollIntoView({block:'start',behavior:'smooth'});return}
 const t=e.target.closest('[data-action]');if(!t)return;const action=t.dataset.action,id=t.dataset.id;
 if(action==='menu'){const nav=$('#site-nav');nav.classList.toggle('open');t.setAttribute('aria-expanded',String(nav.classList.contains('open')))}
 else if(action==='home'){e.preventDefault();category='all';query='';filters={};visibleCount=8;state='SHOP_HOME';history.replaceState(null,'','?state=SHOP_HOME');render();window.scrollTo({top:0,behavior:'smooth'})}
 else if(action==='category'){category=t.dataset.category;query='';filters={};visibleCount=8;state='CATEGORY';history.replaceState(null,'','?state=CATEGORY');render();$('#catalog').scrollIntoView({block:'start',behavior:'smooth'})}
 else if(action==='all'){category='all';query='';filters={};visibleCount=8;state='SHOP_HOME';history.replaceState(null,'','?state=SHOP_HOME');render()}
 else if(action==='favorite'){favorites.has(id)?favorites.delete(id):favorites.add(id);save(storage.favorites,[...favorites]);render()}
 else if(action==='details'){detailId=id;detailQty=byId(id)?.category==='tyres'?4:1;panel='details';renderPanel()}
 else if(action==='add'){let select=t.closest('.shop-card')?.querySelector('.card-qty')||$('#detail-qty');add(id,Number(select?.value)||1)}
 else if(action==='cart'||action==='favorites'||action==='vehicle'||action==='filters'){panel=action;renderPanel()}
 else if(action==='close'){close()}
 else if(action==='backdrop'){close()}
 else if(action==='minus'){adjust(id,-1)}
 else if(action==='plus'){adjust(id,1)}
 else if(action==='remove'){delete cart[id];save(storage.cart,cart);render()}
 else if(action==='checkout'){panel='checkout';renderPanel()}
 else if(action==='reset-filters'){filters={};visibleCount=8;render();if(panel==='filters')renderPanel()}
 else if(action==='more'){visibleCount+=8;render()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();showControls(false)}});
$('#controls-open').addEventListener('click',()=>showControls(true));$('#controls-close').addEventListener('click',()=>showControls(false));$('#controls-hide').addEventListener('click',()=>showControls(false));
$('#state-select').addEventListener('change',e=>{showControls(false);setScenario(e.target.value)});
setScenario(state,true);
