/* Autonomous wheel-alignment prototype: no fetch, product API, forms or external assets. */
const $=(selector,root=document)=>root.querySelector(selector);
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7"/></svg>';
const carIcon='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m4 11 2-5h12l2 5M3 11h18v8H3zM6 19v2m12-2v2M6 15h.01M18 15h.01"/></svg>';
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const states=['CURRENT','LOCAL_CURRENT'];
let state=states.includes(new URLSearchParams(location.search).get('state'))?new URLSearchParams(location.search).get('state'):'CURRENT';
let lastFocus=null;
const isLocal=()=>state==='LOCAL_CURRENT';
const visitWorks=[
 {id:'camry',car:'Toyota Camry',year:'2019',date:'18 сентября 2026',iso:'2026-09-18',items:[['Проверка состояния шин',700],['Сход-развал передней оси',2490],['Замена рулевого наконечника',2800]],total:5990},
 {id:'octavia',car:'Skoda Octavia',year:'2020',date:'12 сентября 2026',iso:'2026-09-12',items:[['Проверка состояния шин',1500],['Ремонт элемента подвески',3600],['Сход-развал двух осей',4600]],total:9700},
 {id:'rio',car:'Kia Rio',year:'2021',date:'8 сентября 2026',iso:'2026-09-08',items:[['Проверка рулевых соединений',900],['Сход-развал передней оси',2490],['Сопутствующая работа',800]],total:4190}
];
const symptoms=[
 ['Автомобиль уводит в сторону','Причин может быть несколько — начнём с проверки состояния автомобиля.'],
 ['Руль стоит неровно','Сравним положение руля и результаты измерения геометрии.'],
 ['Шины изнашиваются неравномерно','Оценим шины и выясним, поможет ли регулировка.'],
 ['После ремонта подвески','Проверим геометрию после замены связанных деталей.'],
 ['После сильного удара колесом','Осмотрим шины и ходовую перед решением о регулировке.'],
 ['Изменилась управляемость','Проверка поможет найти причину, а не угадать её по симптому.']
];
const prechecks=[
 ['Шины','Состояние, повреждения и характер износа.'],
 ['Ходовая','Критические люфты, рычаги, сайлентблоки и шарниры, если они влияют на результат.'],
 ['Рулевое управление','Рулевые соединения и другие причины, которые сначала требуют ремонта.']
];
const steps=[
 ['Уточняем задачу','Что изменилось в поведении автомобиля.'],
 ['Проверяем автомобиль','Осматриваем шины, ходовую и рулевое управление.'],
 ['Измеряем геометрию','Сравниваем параметры с нормативами для конкретной модели.'],
 ['Определяем необходимые работы','По результатам измерения понятно, что именно требует регулировки.'],
 ['Выполняем регулировку','Если состояние автомобиля позволяет получить корректный результат.'],
 ['Контролируем результат','Повторно измеряем параметры после регулировки.']
];
const faq=[
 ['Когда стоит проверить геометрию?','После ремонта подвески или сильного удара колесом параметры стоит проверить даже без явного увода.'],
 ['Когда нужна одна ось, а когда две? Сколько стоит?','Объём определим после измерения. Одна ось — от 2 490 ₽, две — от 4 600 ₽.'],
 ['Что если обнаружен люфт или неисправность ходовой?','Сначала объясним, что нужно устранить. Сход-развал выполнять не будем; оплачивается только диагностика ходовой.'],
 ['Зачем может понадобиться электронная калибровка руля?','Если этого требует процедура модели, после механической регулировки сбрасывают или калибруют датчик угла руля.'],
 ['Почему иногда проверяют высоту подвески или нагрузку?','Когда заводские параметры зависят от высоты подвески или нагрузки, автомобиль готовят по инструкции модели. Универсального веса нет.'],
 ['Что получу после регулировки?','Сравним исходные и контрольные параметры. Формат выдачи отчёта уточните при записи.']
];
function brand(){return '<a class="brand" href="#top" aria-label="КОЛЕСОВИК — к началу страницы"><span class="brand-symbol">К</span><span>КОЛЕСОВИК</span></a>'}
function header(){return '<header id="top" class="next-header next-container">'+brand()+'<nav id="site-nav" class="next-nav" aria-label="Главная навигация"><a href="#symptoms">Когда проверить</a><a href="#precheck">Перед регулировкой</a><a href="#price">Цена</a><a href="#works">Работы</a><a href="#locations">Адрес</a></nav><div class="next-header-actions"><button type="button" class="next-account" data-action="booking">Запись '+arrow+'</button><button type="button" class="next-menu" data-action="menu" aria-label="Открыть меню" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div></header>'}
function breadcrumbs(){return '<nav class="breadcrumbs next-container" aria-label="Путь"><a href="#top">Главная</a><span> / </span><span>Услуги</span><span> / </span>'+(isLocal()?'<a href="?state=CURRENT">Сход-развал</a><span> / </span><span aria-current="page">Подольск</span>':'<span aria-current="page">Сход-развал</span>')+'</nav>'}
function heading(kicker,title,description,id){return '<div class="next-section-heading"><div><div class="eyebrow">'+kicker+'</div><h2 id="'+id+'">'+title+'</h2>'+(description?'<p>'+description+'</p>':'')+'</div></div>'}
function hero(){return '<section class="service-hero next-container" aria-labelledby="page-title"><div class="hero-copy"><div class="eyebrow"><span class="next-eyebrow-line"></span>'+(isLocal()?'КОЛЕСОВИК · ПОДОЛЬСК':'КОЛЕСОВИК · АВТОСЕРВИС')+'</div><h1 id="page-title">'+(isLocal()?'Сход-развал <em>в Подольске</em>':'Сход-<em>развал</em>')+'</h1><p class="hero-lead">Проверим геометрию колёс и при необходимости отрегулируем углы установки по параметрам вашего автомобиля.</p><p class="hero-price">Стоимость — <strong>от 2 490 ₽</strong></p><div class="next-hero-buttons"><button type="button" class="button primary large" data-action="booking">Записаться '+arrow+'</button><button type="button" class="button secondary large" data-action="ask">Спросить</button></div><p class="next-assurance"><span>✓</span><span>Подольск · Станционная, 11/1</span></p></div><div class="hero-visual"><picture><source media="(max-width:767px)" srcset="assets/service-mobile.webp"><img src="assets/service.webp" alt="Сервисная зона КОЛЕСОВИК с постами обслуживания автомобилей" width="1448" height="1086"></picture><div class="photo-caption"><span class="caption-pin">⌖</span><span><strong>Сход-развал</strong><small>Подольск · Станционная, 11/1</small></span><span>↗</span></div></div><div class="hero-bottom"><span>ИЗМЕРЕНИЕ · РЕГУЛИРОВКА · КОНТРОЛЬ</span><span>ПОДОЛЬСК · СТАНЦИОННАЯ, 11/1</span></div></section>'}
function symptomBlock(){return '<section id="symptoms" class="next-section next-container" aria-labelledby="symptoms-title">'+heading('НАЧНИТЕ С СИТУАЦИИ','Когда стоит проверить геометрию','Эти признаки — повод проверить автомобиль, а не готовый диагноз.','symptoms-title')+'<div class="symptom-list">'+symptoms.map((x,i)=>'<div class="symptom-item"><span class="symptom-index">0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></div>').join('')+'</div></section>'}
function precheckBlock(){return '<section id="precheck" class="next-section next-container" aria-labelledby="precheck-title">'+heading('ПЕРЕД РЕГУЛИРОВКОЙ','Сначала проверяем — потом регулируем','Перед регулировкой проверяем шины, ходовую и рулевое управление.','precheck-title')+'<div class="precheck-list">'+prechecks.map((x,i)=>'<div class="precheck-item"><span>0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></div>').join('')+'</div><div class="policy-note"><strong>Если сход-развал сейчас не поможет или корректно выполнить его нельзя — регулировку не делаем.</strong><p>Вы оплачиваете только диагностику ходовой.</p></div></section>'}
function priceBlock(){return '<section id="price" class="next-section next-container" aria-labelledby="price-title">'+heading('ПОНЯТНЫЙ ОРИЕНТИР','Стоимость сход-развала',null,'price-title')+'<div class="alignment-price"><div class="alignment-price-item"><span class="eyebrow">ОДНА ОСЬ</span><strong>от 2 490 ₽</strong></div><div class="alignment-price-item"><span class="eyebrow">ПЕРЕДНЯЯ + ЗАДНЯЯ ОСЬ</span><strong>от 4 600 ₽</strong></div></div><p class="price-policy">Точный объём работ определяется после проверки автомобиля.</p></section>'}
function bookingStrip(){return '<section id="booking" class="booking-strip next-container" aria-label="Запись на сход-развал"><div><div class="eyebrow">СЛЕДУЮЩИЙ ШАГ</div><h2>Запишитесь на сход-развал</h2><p>Не уверены, нужна ли регулировка? Опишите проблему через «Спросить».</p></div><button type="button" class="button primary large" data-action="booking">Записаться '+arrow+'</button></section>'}
function processBlock(){return '<section id="process" class="next-section next-container" aria-labelledby="process-title">'+heading('ПО ПОРЯДКУ','Как проходит работа','От первичной проверки до контрольного измерения.','process-title')+'<ol class="process-list">'+steps.map((x,i)=>'<li><span class="process-index">0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></li>').join('')+'</ol></section>'}
function workCard(w){return '<article class="next-work-card"><div class="next-work-header"><span>'+carIcon+'</span><time datetime="'+w.iso+'">'+w.date+'</time></div><div class="next-work-identity"><h3>'+w.car+'</h3><p>'+w.year+' год · Подольск · DEMO</p></div><ul class="next-work-summary">'+w.items.map(x=>'<li><span>'+x[0]+'</span><b>'+money(x[1])+'</b></li>').join('')+'</ul><div class="next-work-footer"><div><small>Итого за работы · DEMO</small><strong>'+money(w.total)+'</strong></div><button type="button" class="next-work-view" data-action="work" data-id="'+w.id+'">Смотреть '+arrow+'</button></div></article>'}
function oemBlock(){return '<section id="oem" class="next-section next-container" aria-labelledby="oem-title">'+heading('ПО ПРОЦЕДУРЕ МОДЕЛИ','На некоторых автомобилях нужны дополнительные процедуры','Они зависят от требований производителя для конкретной модели.','oem-title')+'<div class="oem-list"><div><span>01</span><div><h3>Электронная калибровка рулевого управления</h3><p>На некоторых автомобилях после механической регулировки требуется сброс или калибровка датчика угла руля, иногда со связанными датчиками. Необходимость определяем по процедуре модели.</p></div></div><div><span>02</span><div><h3>Высота подвески и нагрузка</h3><p>Для некоторых моделей перед измерением нужно проверить высоту подвески или подготовить автомобиль под предусмотренную производителем нагрузку. Универсального значения нагрузки нет.</p></div></div></div></section>'}
function measurementBlock(){return '<section id="measurement" class="next-section next-container" aria-labelledby="measurement-title">'+heading('РЕЗУЛЬТАТ РАБОТЫ','Результат измерения',null,'measurement-title')+'<div class="measurement-flow" aria-label="Схема результата измерений без числовых значений"><div><span class="eyebrow">ДО</span><strong>Исходные параметры</strong></div><span class="measurement-arrow" aria-hidden="true">→</span><div><span class="eyebrow">ПОСЛЕ</span><strong>Контрольные параметры после регулировки</strong></div></div><p class="measurement-caption">Если регулировка выполнена, сравниваем результат до и после.</p><p class="measurement-note">Схема прототипа без числовых значений.</p></section>'}
function worksBlock(){return '<section id="works" class="next-section next-container" aria-labelledby="works-title">'+heading('ОДИН АВТОМОБИЛЬ · НЕСКОЛЬКО РАБОТ',isLocal()?'Примеры посещений в Подольске':'Выполненные работы','Синтетические примеры показывают устройство карточки посещения. Это не реальные заказы и не действующий прайс.','works-title')+'<div class="next-works-grid" aria-label="Синтетические примеры выполненных работ">'+visitWorks.map(workCard).join('')+'</div></section>'}
function relatedBlock(){const items=['Диагностика ходовой','Ремонт ходовой','Шиномонтаж','Шины'];return '<section class="next-section next-container" aria-labelledby="related-title">'+heading('РЯДОМ С ЗАДАЧЕЙ','Смежные услуги',null,'related-title')+'<div class="related-list">'+items.map((x,i)=>'<div class="related-row"><span>0'+(i+1)+'</span><strong>'+x+'</strong>'+arrow+'</div>').join('')+'</div></section>'}
function trustBlock(){return '<section class="next-trust" aria-labelledby="trust-title"><div class="next-container trust-content"><div class="trust-intro"><div class="eyebrow">ПРОЗРАЧНОСТЬ</div><h2 id="trust-title">Работаем<br><em>по измерениям.</em></h2><p>Показываем, на чём основано решение по вашему автомобилю.</p></div><div class="trust-principles"><div><span>01</span><p><strong>Проверяем, а не предполагаем</strong><br>Решение принимаем после осмотра и измерения.</p></div><div><span>02</span><p><strong>Учитываем конкретный автомобиль</strong><br>Используем параметры и процедуры для модели.</p></div><div><span>03</span><p><strong>Показываем результат</strong><br>После работы можно сравнить исходные и контрольные значения.</p></div></div></div></section>'}
function faqBlock(){return '<section class="next-section next-container faq-section" aria-labelledby="faq-title">'+heading('КОРОТКО О ГЛАВНОМ','Частые вопросы',null,'faq-title')+'<div class="faq-list">'+faq.map(x=>'<details><summary>'+x[0]+'<span aria-hidden="true">+</span></summary><p>'+x[1]+'</p></details>').join('')+'</div></section>'}
function locationBlock(){return '<section id="locations" class="next-section next-container" aria-labelledby="locations-title">'+heading('АДРЕС СЕРВИСА',isLocal()?'Как нас найти':'Где проверить геометрию','Подольск · Станционная, 11/1. Маршрут и запись — ниже.','locations-title')+'<div class="locations-layout"><div class="city-groups"><div class="city-group"><div class="city-heading"><h3>Подольск</h3><span>1 адрес</span></div><div class="branch-grid"><article class="branch-card"><span class="branch-mark">К</span><div class="eyebrow">ПОДОЛЬСК</div><h3>КОЛЕСОВИК · Станционная</h3><p>Подольск, Станционная, 11/1</p><div class="branch-divider"></div><dl><div><dt>Режим работы</dt><dd>Уточните перед визитом</dd></div></dl><div class="branch-actions"><button type="button" class="button secondary" data-action="route">Маршрут '+arrow+'</button><button type="button" class="button primary" data-action="booking">Записаться</button></div></article></div></div></div><div class="map-panel" aria-label="Схема местоположения"><div class="map-grid"><span class="map-pin">К</span><span class="map-road road-one"></span><span class="map-road road-two"></span></div><div class="map-caption"><strong>Подольск</strong><small>Станционная, 11/1 · схема для прототипа</small></div></div></div></section>'}
function footer(){return '<footer class="next-footer next-container">'+brand()+'<span>Сервис, которому можно доверить дорогу.</span><button type="button" class="next-footer-login" data-action="booking">Записаться</button><small>© 2026 КОЛЕСОВИК · Локальный дизайн-прототип</small></footer>'}
function render(){document.title=(isLocal()?'Сход-развал в Подольске':'Сход-развал')+' — КОЛЕСОВИК · визуальный прототип';$('#state-select').value=state;$('#technical-key').textContent=state;$('#app').innerHTML='<div class="next-home">'+header()+'<main id="content">'+breadcrumbs()+hero()+symptomBlock()+precheckBlock()+priceBlock()+bookingStrip()+processBlock()+oemBlock()+measurementBlock()+worksBlock()+relatedBlock()+trustBlock()+faqBlock()+locationBlock()+'</main>'+footer()+'</div>'}
function openOverlay(title,body,type='modal'){lastFocus=document.activeElement;$('#overlay-root').innerHTML='<div class="overlay-backdrop" data-action="backdrop"><section class="overlay-panel '+type+'" role="dialog" aria-modal="true" aria-labelledby="overlay-title" tabindex="-1"><div class="overlay-head"><div class="eyebrow">КОЛЕСОВИК · СХОД-РАЗВАЛ</div><button type="button" data-action="close" aria-label="Закрыть">×</button></div><h2 id="overlay-title">'+title+'</h2>'+body+'</section></div>';document.body.classList.add('overlay-open');$('.overlay-panel').focus()}
function closeOverlay(){if(!$('#overlay-root').innerHTML)return;$('#overlay-root').innerHTML='';document.body.classList.remove('overlay-open');if(lastFocus&&lastFocus.isConnected)lastFocus.focus()}
function booking(){openOverlay('Запись на сход-развал','<p>На рабочем сайте здесь откроется выбор даты и времени.</p><dl class="context-list"><div><dt>Услуга</dt><dd>Сход-развал</dd></div><div><dt>Адрес</dt><dd>Подольск · Станционная, 11/1</dd></div></dl><p class="overlay-note">В этом макете запись не создаётся.</p><button type="button" class="button primary" data-action="close">Вернуться на страницу</button>','booking-drawer')}
function ask(){openOverlay('Спросить','<p>Не уверены, нужен ли сход-развал? На рабочем сайте здесь откроется диалог с сервисом.</p><p class="overlay-note">В этом макете сообщение не отправляется.</p><button type="button" class="button primary" data-action="close">Понятно</button>','booking-drawer')}
function showWork(id){const w=visitWorks.find(x=>x.id===id);if(!w)return;openOverlay('Выполненные работы','<div class="eyebrow">DEMO · СИНТЕТИЧЕСКИЙ ПРИМЕР</div><h3>'+w.car+' · '+w.year+'</h3><time datetime="'+w.iso+'">'+w.date+'</time><ul class="detail-lines">'+w.items.map(x=>'<li><span>'+x[0]+'</span><b>'+money(x[1])+'</b></li>').join('')+'</ul><div class="detail-total"><span>Итого за работы</span><strong>'+money(w.total)+'</strong></div><div class="overlay-actions"><button type="button" class="button secondary" data-action="ask">Спросить</button><button type="button" class="button primary" data-action="booking">Записаться</button></div>')}
function route(){openOverlay('Маршрут к сервису','<h3>КОЛЕСОВИК · Станционная</h3><p>Подольск, Станционная, 11/1</p><p class="overlay-note">Адрес действующего сервиса. В этом макете внешняя карта не открывается.</p><button type="button" class="button primary" data-action="close">Закрыть</button>')}
function controls(open){$('#prototype-controls').hidden=!open;$('#controls-open').setAttribute('aria-expanded',String(open));if(open){lastFocus=document.activeElement;$('.controls-panel').focus()}else if(lastFocus&&lastFocus.isConnected)lastFocus.focus()}
document.addEventListener('click',e=>{if(e.target.classList&&e.target.classList.contains('overlay-backdrop')){closeOverlay();return}const t=e.target.closest('button');if(!t)return;const action=t.dataset.action;if(action==='menu'){const nav=$('#site-nav');nav.classList.toggle('open');t.setAttribute('aria-expanded',String(nav.classList.contains('open')));return}if(action==='close'){closeOverlay();return}if(action==='booking'){closeOverlay();booking();return}if(action==='ask'){closeOverlay();ask();return}if(action==='work'){showWork(t.dataset.id);return}if(action==='route'){route()}});
$('#controls-open').addEventListener('click',()=>controls(true));$('#controls-close').addEventListener('click',()=>controls(false));$('#controls-hide').addEventListener('click',()=>controls(false));
$('#state-select').addEventListener('change',e=>{state=e.target.value;history.replaceState(null,'',location.pathname+'?state='+state);render();controls(false);scrollTo(0,0)});
const readTheme=()=>{try{return localStorage.getItem('alignment-prototype-theme')||'light'}catch{return 'light'}};
function applyTheme(value){document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value}
$('#theme-select').value=readTheme();$('#theme-select').addEventListener('change',e=>{try{localStorage.setItem('alignment-prototype-theme',e.target.value)}catch{}applyTheme(e.target.value)});matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(readTheme()==='system')applyTheme('system')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#prototype-controls').hidden)controls(false);else closeOverlay()}if(e.key==='p'&&e.altKey&&e.shiftKey)controls($('#prototype-controls').hidden);if(e.key==='Tab'){const panel=!$('#prototype-controls').hidden?$('.controls-panel'):$('.overlay-panel');if(!panel)return;const items=[...panel.querySelectorAll('button,select,a')].filter(x=>!x.disabled);if(!items.length)return;if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0].focus()}}});
render();
