/* Autonomous diagnostics page prototype: no fetch, product API, forms or external assets. */
const $=(selector,root=document)=>root.querySelector(selector);
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7"/></svg>';
const carIcon='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m4 11 2-5h12l2 5M3 11h18v8H3zM6 19v2m12-2v2M6 15h.01M18 15h.01"/></svg>';
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const states=['CURRENT','LOCAL_CURRENT'];
let state=states.includes(new URLSearchParams(location.search).get('state'))?new URLSearchParams(location.search).get('state'):'CURRENT';
let lastFocus=null;
const isLocal=()=>state==='LOCAL_CURRENT';
const visitWorks=[
 {id:'camry',car:'Toyota Camry',year:'2019',date:'18 сентября 2026',iso:'2026-09-18',items:[['Диагностика ходовой части',1800],['Проверка креплений',900],['Замена втулок стабилизатора',2600]],total:5300},
 {id:'octavia',car:'Skoda Octavia',year:'2020',date:'12 сентября 2026',iso:'2026-09-12',items:[['Компьютерная диагностика',1500],['Проверка системы зажигания',1200],['Замена свечей зажигания',2100]],total:4800},
 {id:'rio',car:'Kia Rio',year:'2021',date:'8 сентября 2026',iso:'2026-09-08',items:[['Диагностика ходовой части',1500],['Проверка состояния колёс',700],['Проверка после осмотра',500]],total:2700}
];
const symptoms=[
 ['Появился новый звук','Расскажите, когда он слышен: на ходу, при повороте или на неровной дороге.'],
 ['Горит индикатор ошибки','Проверка поможет понять, с чем связан сигнал.'],
 ['Машина ведёт себя иначе','Изменились разгон, переключение передач или управляемость.'],
 ['Есть вопросы к ходовой','Беспокоят стук, вибрация или ощущение неровного хода.'],
 ['Перед дальней поездкой','Хотите узнать состояние автомобиля до дороги.'],
 ['Перед ремонтом','Сначала нужно выяснить причину неисправности и следующий шаг.']
];
const directions=[
 ['Двигатель','Проверка по заявленной проблеме.'],
 ['Подвеска и ходовая','Осмотр узлов, связанных с поведением автомобиля.'],
 ['Трансмиссия','Проверка при вопросах к работе передачи тяги.'],
 ['Состояние колёс','Осмотр колёс в контексте жалобы.'],
 ['Компьютерная диагностика','Проверка электронных сигналов и связанных узлов.']
];
const steps=[
 ['Вы описываете проблему','Что изменилось и когда это заметно.'],
 ['Мы проверяем автомобиль','Выбираем необходимые направления проверки.'],
 ['Показываем найденное','Объясняем, что обнаружено при осмотре.'],
 ['Даём понятные рекомендации','Что требует внимания сейчас, а что можно запланировать.'],
 ['Решение остаётся за вами','Ремонт не начинается автоматически после диагностики.']
];
const faq=[
 ['Что входит в диагностику?','Направления проверки зависят от задачи. На странице услуги указаны двигатель, подвеска, трансмиссия, колёса, ключевые узлы и компьютерная диагностика.'],
 ['Сколько занимает проверка?','Ориентир — 30 минут. Для конкретной задачи время уточняют при записи.'],
 ['Можно приехать с конкретным симптомом?','Да. Опишите, что изменилось и когда это происходит. Один симптом сам по себе не указывает на определённую неисправность.'],
 ['Нужно ли сразу делать ремонт?','Нет. После проверки объяснят найденное и рекомендации; решение о дальнейших работах остаётся за вами.'],
 ['Сколько стоит диагностика?','Стоимость начинается от 1 500 ₽. Итоговую сумму уточняют для нужного объёма проверки до начала работ.'],
 ['Как записаться?','Нажмите «Записаться». На рабочем сайте откроется существующий выбор даты и времени.']
];
function brand(){return '<a class="brand" href="#top" aria-label="КОЛЕСОВИК — к началу страницы"><span class="brand-symbol">К</span><span>КОЛЕСОВИК</span></a>'}
function header(){return '<header id="top" class="next-header next-container">'+brand()+'<nav id="site-nav" class="next-nav" aria-label="Главная навигация"><a href="#symptoms">Когда нужна</a><a href="#scope">Что проверяем</a><a href="#price">Цена</a><a href="#works">Работы</a><a href="#locations">Адрес</a></nav><div class="next-header-actions"><button type="button" class="next-account" data-action="booking">Запись '+arrow+'</button><button type="button" class="next-menu" data-action="menu" aria-label="Открыть меню" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div></header>'}
function breadcrumbs(){return '<nav class="breadcrumbs next-container" aria-label="Путь"><a href="#top">Главная</a><span> / </span><span>Услуги</span><span> / </span>'+(isLocal()?'<a href="?state=CURRENT">Диагностика</a><span> / </span><span aria-current="page">Подольск</span>':'<span aria-current="page">Диагностика</span>')+'</nav>'}
function heading(kicker,title,description,id){return '<div class="next-section-heading"><div><div class="eyebrow">'+kicker+'</div><h2 id="'+id+'">'+title+'</h2>'+(description?'<p>'+description+'</p>':'')+'</div></div>'}
function hero(){return '<section class="service-hero next-container" aria-labelledby="page-title"><div class="hero-copy"><div class="eyebrow"><span class="next-eyebrow-line"></span>'+(isLocal()?'КОЛЕСОВИК · ПОДОЛЬСК':'КОЛЕСОВИК · АВТОСЕРВИС')+'</div><h1 id="page-title">'+(isLocal()?'Диагностика автомобиля <em>в Подольске</em>':'Диагностика <em>автомобиля</em>')+'</h1><p class="hero-lead">'+(isLocal()?'В Подольске проверим автомобиль, покажем найденное и объясним, что делать дальше.':'Поможем разобраться, что изменилось в работе автомобиля. Проверим причину и объясним следующий шаг понятным языком.')+'</p><div class="next-hero-buttons"><button type="button" class="button primary large" data-action="booking">Записаться '+arrow+'</button><button type="button" class="button secondary large" data-action="ask">Спросить</button></div><p class="next-assurance"><span>✓</span><span>Подольск · Станционная, 11/1</span></p></div><div class="hero-visual"><picture><source media="(max-width:767px)" srcset="assets/service-mobile.webp"><img src="assets/service.webp" alt="Автомобиль в сервисной зоне КОЛЕСОВИК" width="1448" height="1086"></picture><div class="photo-caption"><span class="caption-pin">⌖</span><span><strong>Проверка автомобиля</strong><small>Подольск · Станционная, 11/1</small></span><span>↗</span></div></div><div class="hero-bottom"><span>ДИАГНОСТИКА · ПОНЯТНЫЙ СЛЕДУЮЩИЙ ШАГ</span><span>ПОДОЛЬСК · СТАНЦИОННАЯ, 11/1</span></div></section>'}
function symptomBlock(){return '<section id="symptoms" class="next-section next-container" aria-labelledby="symptoms-title">'+heading('НАЧНИТЕ С СИТУАЦИИ',isLocal()?'С чем можно приехать':'Когда нужна диагностика','Эти признаки помогают описать задачу. Причину определит проверка автомобиля.','symptoms-title')+'<div class="symptom-list">'+symptoms.map((x,i)=>'<div class="symptom-item"><span class="symptom-index">0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></div>').join('')+'</div></section>'}
function scopeBlock(){return '<section id="scope" class="next-section next-container" aria-labelledby="scope-title">'+heading('НАПРАВЛЕНИЯ ПРОВЕРКИ','Что проверяем','Конкретный состав зависит от вопроса, с которым вы приехали.','scope-title')+'<div class="scope-list">'+directions.map((x,i)=>'<div class="scope-item"><span>0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></div>').join('')+'</div></section>'}
function priceBlock(){return '<section id="price" class="next-section next-container" aria-labelledby="price-title">'+heading('СТОИМОСТЬ И ВРЕМЯ','Понятный ориентир','Окончательный объём проверки уточним по вашей задаче.','price-title')+'<div class="diagnostic-price"><div class="diagnostic-price-main"><span class="eyebrow">ДИАГНОСТИКА АВТОМОБИЛЯ</span><strong>от 1 500 ₽</strong><p>Стоимость конкретной проверки уточним до начала работ.</p></div><div class="diagnostic-time"><span class="eyebrow">ОРИЕНТИР ПО ВРЕМЕНИ</span><strong>30 минут</strong><p>Время зависит от задачи; уточним его при записи.</p></div></div></section>'}
function bookingStrip(){return '<section id="booking" class="booking-strip next-container" aria-label="Запись на диагностику"><div><div class="eyebrow">СЛЕДУЮЩИЙ ШАГ</div><h2>Запишитесь на диагностику</h2><p>Подольск · Станционная, 11/1. Если хотите описать симптом заранее, нажмите «Спросить».</p></div><button type="button" class="button primary large" data-action="booking">Записаться '+arrow+'</button></section>'}
function resultBlock(){return '<section id="result" class="next-section next-container" aria-labelledby="result-title">'+heading('ОТ ПРОБЛЕМЫ К РЕШЕНИЮ','Что будет после проверки','Проверка помогает понять состояние машины. Ремонт обсуждается отдельно.','result-title')+'<ol class="process-list">'+steps.map((x,i)=>'<li><span class="process-index">0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></li>').join('')+'</ol><div class="result-outcomes"><strong>Что может быть дальше</strong><div><span>Требует внимания сейчас</span><span>Можно запланировать</span><span>Работы не нужны</span></div></div></section>'}
function workCard(w){return '<article class="next-work-card"><div class="next-work-header"><span>'+carIcon+'</span><time datetime="'+w.iso+'">'+w.date+'</time></div><div class="next-work-identity"><h3>'+w.car+'</h3><p>'+w.year+' год · Подольск · DEMO</p></div><ul class="next-work-summary">'+w.items.map(x=>'<li><span>'+x[0]+'</span><b>'+money(x[1])+'</b></li>').join('')+'</ul><div class="next-work-footer"><div><small>Итого за работы · DEMO</small><strong>'+money(w.total)+'</strong></div><button type="button" class="next-work-view" data-action="work" data-id="'+w.id+'">Смотреть '+arrow+'</button></div></article>'}
function worksBlock(){return '<section id="works" class="next-section next-container" aria-labelledby="works-title">'+heading('ОДИН АВТОМОБИЛЬ · НЕСКОЛЬКО РАБОТ',isLocal()?'Примеры посещений в Подольске':'Выполненные работы','Синтетические примеры показывают устройство карточки посещения. Это не реальные заказы и не действующий прайс.','works-title')+'<div class="next-works-grid" aria-label="Синтетические примеры выполненных работ">'+visitWorks.map(workCard).join('')+'</div></section>'}
function relatedBlock(){const items=['Ремонт ходовой части','Техническое обслуживание','Ремонт двигателя','Развал-схождение'];return '<section class="next-section next-container" aria-labelledby="related-title">'+heading('ПОСЛЕ ДИАГНОСТИКИ','Смежные услуги','Направление дальнейших работ определяют по результату проверки.','related-title')+'<div class="related-list">'+items.map((x,i)=>'<div class="related-row"><span>0'+(i+1)+'</span><strong>'+x+'</strong><span class="related-caption">По результату проверки</span>'+arrow+'</div>').join('')+'</div></section>'}
function trustBlock(){return '<section class="next-trust" aria-labelledby="trust-title"><div class="next-container trust-content"><div class="trust-intro"><div class="eyebrow">ПРОЗРАЧНОСТЬ</div><h2 id="trust-title">Сначала<br><em>разобраться.</em></h2><p>Проверка нужна, чтобы понять проблему и принять решение без давления.</p></div><div class="trust-principles"><div><span>01</span><p><strong>Показываем найденное</strong><br>Объясняем результат простыми словами.</p></div><div><span>02</span><p><strong>Расставляем приоритеты</strong><br>Что требует внимания сейчас, а что можно запланировать.</p></div><div><span>03</span><p><strong>Решение за вами</strong><br>Диагностика не означает автоматический ремонт.</p></div></div></div></section>'}
function faqBlock(){return '<section class="next-section next-container faq-section" aria-labelledby="faq-title">'+heading('КОРОТКО О ГЛАВНОМ','Частые вопросы',null,'faq-title')+'<div class="faq-list">'+faq.map(x=>'<details><summary>'+x[0]+'<span aria-hidden="true">+</span></summary><p>'+x[1]+'</p></details>').join('')+'</div></section>'}
function locationBlock(){return '<section id="locations" class="next-section next-container" aria-labelledby="locations-title">'+heading('АДРЕС СЕРВИСА',isLocal()?'Как нас найти':'Где пройти диагностику','Подольск · Станционная, 11/1. Маршрут и запись — ниже.','locations-title')+'<div class="locations-layout"><div class="city-groups"><div class="city-group"><div class="city-heading"><h3>Подольск</h3><span>1 адрес</span></div><div class="branch-grid"><article class="branch-card"><span class="branch-mark">К</span><div class="eyebrow">ПОДОЛЬСК</div><h3>КОЛЕСОВИК · Станционная</h3><p>Подольск, Станционная, 11/1</p><div class="branch-divider"></div><dl><div><dt>Режим работы</dt><dd>Уточните перед визитом</dd></div></dl><div class="branch-actions"><button type="button" class="button secondary" data-action="route">Маршрут '+arrow+'</button><button type="button" class="button primary" data-action="booking">Записаться</button></div></article></div></div></div><div class="map-panel" aria-label="Схема местоположения"><div class="map-grid"><span class="map-pin">К</span><span class="map-road road-one"></span><span class="map-road road-two"></span></div><div class="map-caption"><strong>Подольск</strong><small>Станционная, 11/1 · схема для прототипа</small></div></div></div></section>'}
function footer(){return '<footer class="next-footer next-container">'+brand()+'<span>Сервис, которому можно доверить дорогу.</span><button type="button" class="next-footer-login" data-action="booking">Записаться</button><small>© 2026 КОЛЕСОВИК · Локальный дизайн-прототип</small></footer>'}
function render(){document.title=(isLocal()?'Диагностика автомобиля в Подольске':'Диагностика автомобиля')+' — КОЛЕСОВИК · визуальный прототип';$('#state-select').value=state;$('#technical-key').textContent=state;$('#app').innerHTML='<div class="next-home">'+header()+'<main id="content">'+breadcrumbs()+hero()+symptomBlock()+scopeBlock()+priceBlock()+bookingStrip()+resultBlock()+worksBlock()+relatedBlock()+trustBlock()+faqBlock()+locationBlock()+'</main>'+footer()+'</div>'}
function openOverlay(title,body,type='modal'){lastFocus=document.activeElement;$('#overlay-root').innerHTML='<div class="overlay-backdrop" data-action="backdrop"><section class="overlay-panel '+type+'" role="dialog" aria-modal="true" aria-labelledby="overlay-title" tabindex="-1"><div class="overlay-head"><div class="eyebrow">КОЛЕСОВИК · ДИАГНОСТИКА</div><button type="button" data-action="close" aria-label="Закрыть">×</button></div><h2 id="overlay-title">'+title+'</h2>'+body+'</section></div>';document.body.classList.add('overlay-open');$('.overlay-panel').focus()}
function closeOverlay(){if(!$('#overlay-root').innerHTML)return;$('#overlay-root').innerHTML='';document.body.classList.remove('overlay-open');if(lastFocus&&lastFocus.isConnected)lastFocus.focus()}
function booking(){openOverlay('Запись на диагностику','<p>На рабочем сайте здесь откроется выбор даты и времени.</p><dl class="context-list"><div><dt>Услуга</dt><dd>Диагностика автомобиля</dd></div><div><dt>Адрес</dt><dd>Подольск · Станционная, 11/1</dd></div></dl><p class="overlay-note">В этом макете запись не создаётся.</p><button type="button" class="button primary" data-action="close">Вернуться на страницу</button>','booking-drawer')}
function ask(){openOverlay('Спросить','<p>На рабочем сайте здесь откроется диалог с сервисом.</p><p class="overlay-note">В этом макете сообщение не отправляется.</p><button type="button" class="button primary" data-action="close">Понятно</button>','booking-drawer')}
function showWork(id){const w=visitWorks.find(x=>x.id===id);if(!w)return;openOverlay('Выполненные работы','<div class="eyebrow">DEMO · СИНТЕТИЧЕСКИЙ ПРИМЕР</div><h3>'+w.car+' · '+w.year+'</h3><time datetime="'+w.iso+'">'+w.date+'</time><ul class="detail-lines">'+w.items.map(x=>'<li><span>'+x[0]+'</span><b>'+money(x[1])+'</b></li>').join('')+'</ul><div class="detail-total"><span>Итого за работы</span><strong>'+money(w.total)+'</strong></div><div class="overlay-actions"><button type="button" class="button secondary" data-action="ask">Спросить</button><button type="button" class="button primary" data-action="booking">Записаться</button></div>')}
function route(){openOverlay('Маршрут к сервису','<h3>КОЛЕСОВИК · Станционная</h3><p>Подольск, Станционная, 11/1</p><p class="overlay-note">Адрес действующего сервиса. В этом макете внешняя карта не открывается.</p><button type="button" class="button primary" data-action="close">Закрыть</button>')}
function controls(open){$('#prototype-controls').hidden=!open;$('#controls-open').setAttribute('aria-expanded',String(open));if(open){lastFocus=document.activeElement;$('.controls-panel').focus()}else if(lastFocus&&lastFocus.isConnected)lastFocus.focus()}
document.addEventListener('click',e=>{if(e.target.classList&&e.target.classList.contains('overlay-backdrop')){closeOverlay();return}const t=e.target.closest('button');if(!t)return;const action=t.dataset.action;if(action==='menu'){const nav=$('#site-nav');nav.classList.toggle('open');t.setAttribute('aria-expanded',String(nav.classList.contains('open')));return}if(action==='close'){closeOverlay();return}if(action==='booking'){closeOverlay();booking();return}if(action==='ask'){closeOverlay();ask();return}if(action==='work'){showWork(t.dataset.id);return}if(action==='route'){route()}});
$('#controls-open').addEventListener('click',()=>controls(true));$('#controls-close').addEventListener('click',()=>controls(false));$('#controls-hide').addEventListener('click',()=>controls(false));
$('#state-select').addEventListener('change',e=>{state=e.target.value;history.replaceState(null,'',location.pathname+'?state='+state);render();controls(false);scrollTo(0,0)});
const readTheme=()=>{try{return localStorage.getItem('diag-prototype-theme')||'light'}catch{return 'light'}};
function applyTheme(value){document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value}
$('#theme-select').value=readTheme();$('#theme-select').addEventListener('change',e=>{try{localStorage.setItem('diag-prototype-theme',e.target.value)}catch{}applyTheme(e.target.value)});matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(readTheme()==='system')applyTheme('system')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#prototype-controls').hidden)controls(false);else closeOverlay()}if(e.key==='p'&&e.altKey&&e.shiftKey)controls($('#prototype-controls').hidden);if(e.key==='Tab'){const panel=!$('#prototype-controls').hidden?$('.controls-panel'):$('.overlay-panel');if(!panel)return;const items=[...panel.querySelectorAll('button,select,a')].filter(x=>!x.disabled);if(!items.length)return;if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0].focus()}}});
render();
