/* Static, self-contained service page. No fetch, forms, product endpoints or external assets. */
const $=(s,root=document)=>root.querySelector(s);
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7"/></svg>';
const car='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m4 11 2-5h12l2 5M3 11h18v8H3zM6 19v2m12-2v2M6 15h.01M18 15h.01"/></svg>';
const tyre='<svg viewBox="0 0 200 160" aria-hidden="true"><ellipse cx="100" cy="82" rx="61" ry="70" fill="none" stroke="currentColor" stroke-width="24"/><ellipse cx="100" cy="82" rx="60" ry="69" fill="none" stroke="var(--surface-1)" stroke-width="2" stroke-dasharray="5 5"/><ellipse cx="100" cy="82" rx="42" ry="51" fill="var(--surface-2)" stroke="var(--border-2)" stroke-width="2"/><ellipse cx="100" cy="82" rx="24" ry="30" fill="var(--surface-1)" stroke="var(--border-2)" stroke-width="2"/><circle cx="100" cy="82" r="7" fill="var(--text-3)"/><path d="M72 21l7 10m42-10-7 10M59 42l11 5m60-5-11 5M40 70l15 2m90-2-15 2M42 101l14-3m88 3-14-3M59 124l11-6m60 6-11-6M78 143l5-12m39 12-5-12" fill="none" stroke="var(--surface-1)" stroke-width="4" stroke-linecap="round"/></svg>';
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const states=['MASTER_CURRENT','MASTER_NETWORK','CITY_CURRENT','CITY_MULTI_BRANCH','CITY_INSUFFICIENT_DATA'];
let state=states.includes(new URLSearchParams(location.search).get('state'))?new URLSearchParams(location.search).get('state'):'MASTER_CURRENT';
let season='Популярные',lastFocus=null,selectedBranch=null;
const works=[
 {id:'camry',car:'Toyota Camry',year:'2019',date:'18 сентября 2026',iso:'2026-09-18',city:'Подольск',items:[['Шиномонтаж комплекта',3600],['Балансировка колёс',1800],['Проверка давления',600]],total:6000},
 {id:'rio',car:'Kia Rio',year:'2021',date:'15 сентября 2026',iso:'2026-09-15',city:'Подольск',items:[['Ремонт прокола',1400],['Шиномонтаж двух колёс',2000],['Балансировка',900]],total:4300},
 {id:'octavia',car:'Skoda Octavia',year:'2020',date:'12 сентября 2026',iso:'2026-09-12',city:'Подольск',items:[['Шиномонтаж комплекта',4200],['Проверка дисков',800],['Замена вентиля',500]],total:5500}
];
const tyres=[
 {brand:'Nordway',model:'Iceform X5',size:'205/55 R16',season:'Зимние',tag:'Шипованная · XL',price:8490},
 {brand:'Vector',model:'CityTour Pro',size:'225/50 R17',season:'Летние',tag:'XL',price:11900},
 {brand:'Polar',model:'Gripline 7',size:'215/60 R16',season:'Зимние',tag:'RunFlat',price:10200},
 {brand:'Volna',model:'Season One',size:'195/65 R15',season:'Всесезонные',tag:'Для города',price:7900},
 {brand:'Atlas',model:'Roadline S',size:'205/60 R16',season:'Летние',tag:'Комфорт',price:9100}
];
const current={id:'podolsk-station',city:'Подольск',name:'КОЛЕСОВИК · Станционная',address:'Станционная, 11/1',real:true};
const demo=[
 {id:'podolsk-south-demo',city:'Подольск',name:'DEMO · Южный филиал',address:'Демонстрационный адрес · Подольск',real:false},
 {id:'moscow-north-demo',city:'Москва',name:'DEMO · Северный филиал',address:'Демонстрационный адрес · Москва',real:false},
 {id:'moscow-west-demo',city:'Москва',name:'DEMO · Западный филиал',address:'Демонстрационный адрес · Москва',real:false},
 {id:'tula-demo',city:'Тула',name:'DEMO · Городской филиал',address:'Демонстрационный адрес · Тула',real:false}
];
const isCity=()=>state.startsWith('CITY_');
const insufficient=()=>state==='CITY_INSUFFICIENT_DATA';
const future=()=>state==='MASTER_NETWORK'||state==='CITY_MULTI_BRANCH';
function branches(){return state==='MASTER_NETWORK'?[current,...demo]:state==='CITY_MULTI_BRANCH'?[current,demo[0]]:[current]}
function brand(){return '<a class="brand" href="#top" aria-label="КОЛЕСОВИК — к началу страницы"><span class="brand-symbol">К</span><span>КОЛЕСОВИК</span></a>'}
function header(){return `<header id="top" class="next-header next-container">${brand()}<nav id="site-nav" class="next-nav" aria-label="Главная навигация"><a href="#price">Цены</a><a href="#works">Работы</a><a href="#tires">Шины</a><a href="#locations">Филиалы</a></nav><div class="next-header-actions"><button type="button" class="next-account" data-action="booking">Запись ${arrow}</button><button type="button" class="next-menu" data-action="menu" aria-label="Открыть меню" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div></header>`}
function breadcrumbs(){return `<nav class="breadcrumbs next-container" aria-label="Путь"><a href="#top">Главная</a><span> / </span><span>Услуги</span><span> / </span>${isCity()?'<a href="?state=MASTER_CURRENT">Шиномонтаж</a><span> / </span><span aria-current="page">Подольск</span>':'<span aria-current="page">Шиномонтаж</span>'}</nav>`}
function hero(){const city=isCity();return `<section class="service-hero next-container" aria-labelledby="page-title"><div class="hero-copy"><div class="eyebrow"><span class="next-eyebrow-line"></span>${city?'КОЛЕСОВИК · ПОДОЛЬСК':'КОЛЕСОВИК · СЕРВИСНАЯ ЭКОСИСТЕМА'}</div><h1 id="page-title">${city?'Шиномонтаж <em>в Подольске</em>':'Шиномонтаж'}</h1><p class="hero-lead">${city?'Выберите филиал, уточните условия для своих колёс и запишитесь на удобное время.':'Смена сезонного комплекта, монтаж и балансировка колёс. Выберите город и филиал, чтобы узнать условия для своего автомобиля.'}</p><div class="next-hero-buttons"><button type="button" class="button primary large" data-action="booking">Записаться ${arrow}</button><button type="button" class="button secondary large" data-action="ask">Спросить</button></div><p class="next-assurance"><span>✓</span><span>${city?'Подольск · Станционная, 11/1':'Выберите город и филиал для записи и точной стоимости'}</span></p></div><div class="hero-visual"><picture><source media="(max-width:767px)" srcset="assets/service-mobile.webp"><img src="assets/service.webp" alt="Колесо автомобиля в сервисной зоне КОЛЕСОВИК" width="1448" height="1086"></picture><div class="photo-caption"><span class="caption-pin">⌖</span><span><strong>Сервис рядом с вами</strong><small>${city?'Подольск · Станционная, 11/1':'КОЛЕСОВИК · выберите филиал'}</small></span><span>↗</span></div></div><div class="hero-bottom"><span>СЕРВИС С ПОНЯТНЫМ СЛЕДУЮЩИМ ШАГОМ</span><span>${city?'ПОДОЛЬСК · ЛОКАЛЬНЫЙ КОНТЕКСТ':'ГОРОДА И ФИЛИАЛЫ СЕТИ'}</span></div></section>`}
function heading(kicker,title,description,id){return `<div class="next-section-heading"><div><div class="eyebrow">${kicker}</div><h2 id="${id}">${title}</h2>${description?`<p>${description}</p>`:''}</div></div>`}
function facts(){return `<section class="facts-section next-section next-container" aria-labelledby="facts-title">${heading('ПЕРЕД ВИЗИТОМ',isCity()?'Условия в Подольске':'От чего зависит стоимость','Точный состав и итог определяются после выбора условий. Здесь нет общей цены для всей сети.','facts-title')}<div class="fact-list"><div><span>01</span><strong>Размер колеса</strong><p>Диаметр и параметры комплекта влияют на состав работ.</p></div><div><span>02</span><strong>Автомобиль</strong><p>Для разных типов автомобиля условия могут отличаться.</p></div><div><span>03</span><strong>Особые условия</strong><p>RunFlat и состояние дисков уточняются до расчёта.</p></div><div><span>04</span><strong>Место обслуживания</strong><p>${isCity()?'Стоимость уточняется для выбранного филиала Подольска.':'Цена относится к выбранному городу и филиалу, а не к сети в целом.'}</p></div></div></section>`}
function bookingStrip(){return `<section id="booking" class="booking-strip next-container" aria-label="Запись на шиномонтаж"><div><div class="eyebrow">СЛЕДУЮЩИЙ ШАГ</div><h2>${isCity()?'Запишитесь в выбранный филиал':'Выберите место и запишитесь'}</h2><p>${isCity()?'Услуга и город уже выбраны. Филиал уточняется при записи.':'Шиномонтаж выбран. Далее — город, филиал и доступное время.'}</p></div><button type="button" class="button primary large" data-action="booking">Записаться ${arrow}</button></section>`}
function price(){const rows=[['R13–R15','Компактные колёса'],['R16','Распространённый размер'],['R17','Средний размер'],['R18','Крупный размер'],['R19+','Большой диаметр'],['RunFlat','Особые условия']];return `<section id="price" class="next-section next-container" aria-labelledby="price-title">${heading('КОНТЕКСТ ЦЕНЫ',isCity()?'Стоимость шиномонтажа в Подольске':'Стоимость без сюрпризов','Сценарии показывают, что нужно уточнить. Актуальную сумму подтвердит выбранный филиал.','price-title')}<div class="price-layout"><div class="price-list">${rows.map(([size,label])=>`<div class="price-row"><span class="price-size">${size}</span><strong>${label}</strong><span class="price-value">Уточнить в филиале</span></div>`).join('')}</div><aside class="price-aside"><div class="eyebrow">ЦЕНА ПРИВЯЗАНА К ФИЛИАЛУ</div><p>${isCity()?'Подольск · Станционная, 11/1. Подтверждённый прайс для этой композиции не предоставлен.':'Федерального единого тарифа здесь нет. Сначала выберите город и филиал.'}</p><button type="button" class="text-link" data-action="full-price">Полный прайс ${arrow}</button></aside></div></section>`}
function workCard(w){return `<article class="next-work-card"><div class="next-work-header"><span>${car}</span><time datetime="${w.iso}">${w.date}</time></div><div class="next-work-identity"><h3>${w.car}</h3><p>${w.year} год · ${w.city} · DEMO</p></div><ul class="next-work-summary">${w.items.map(x=>`<li><span>${x[0]}</span><b>${money(x[1])}</b></li>`).join('')}</ul><div class="next-work-footer"><div><small>Итого за работы · DEMO</small><strong>${money(w.total)}</strong></div><button type="button" class="next-work-view" data-action="work" data-id="${w.id}">Смотреть ${arrow}</button></div></article>`}
function worksSection(){return `<section id="works" class="next-section next-container" aria-labelledby="works-title">${heading('ОДИН АВТОМОБИЛЬ · НЕСКОЛЬКО РАБОТ',isCity()?'Работы в Подольске':'Выполненные работы','Синтетические примеры показывают состав одного посещения. Не являются реальными заказами или текущим прайсом.','works-title')}<div class="next-works-grid" aria-label="Примеры выполненных работ">${works.map(workCard).join('')}</div></section>`}
function tyreCard(t){return `<article class="next-product-card"><div class="next-product-media">${tyre}<span>${t.season} · DEMO</span></div><div class="next-product-identity"><span class="next-product-brand">${t.brand}</span><h3>${t.model}</h3><p class="next-product-size">${t.size}</p><div class="next-product-tags"><span>${t.tag}</span></div></div><div class="next-product-price"><strong>${money(t.price)}</strong><small>за 1 шт. · DEMO</small></div><div class="next-product-availability"><span>Пример товарной карточки</span><small>Наличие и получение уточняются</small></div><button type="button" class="next-product-buy" data-action="tyre" data-id="${t.model}">Подробнее ${arrow}</button></article>`}
function tyresSection(){const filtered=season==='Популярные'?tyres:tyres.filter(t=>t.season===season);return `<section id="tires" class="next-section next-container" aria-labelledby="tyres-title">${heading('ШИНЫ ДЛЯ ВАШЕГО АВТОМОБИЛЯ','Популярные шины','Демонстрационные товары и цены. Локальное наличие не подтверждено.','tyres-title')}<div class="tyre-toolbar"><div class="category-tabs" role="group" aria-label="Сезон шин">${['Популярные','Летние','Зимние','Всесезонные'].map(s=>`<button type="button" data-season="${s}" aria-pressed="${s===season}">${s}</button>`).join('')}</div><a class="text-link" href="#tires" data-action="all-tyres">Смотреть все шины ${arrow}</a></div><div class="next-products-grid" aria-label="Демонстрационные шины">${filtered.map(tyreCard).join('')}</div></section>`}
function related(){return `<section class="next-section next-container" aria-labelledby="related-title">${heading('РЯДОМ С УСЛУГОЙ','Смежные работы',null,'related-title')}<div class="related-list">${['Балансировка','Ремонт шин','Ремонт дисков','Сезонное хранение'].map((x,i)=>`<div class="related-row"><span>0${i+1}</span><strong>${x}</strong><span class="related-caption">Уточнить доступность</span>${arrow}</div>`).join('')}</div></section>`}
function proof(){return `<section class="next-trust" aria-labelledby="proof-title"><div class="next-container trust-content"><div class="trust-intro"><div class="eyebrow">ПОДХОД</div><h2 id="proof-title">Точно.<br><em>По делу.</em></h2><p>Работу и её стоимость объясняют в контексте вашего автомобиля и филиала.</p></div><div class="trust-principles"><div><span>01</span><p><strong>Оборудование</strong><br>Состав работ и оснащение уточняются для филиала.</p></div><div><span>02</span><p><strong>Понятная стоимость</strong><br>Итог зависит от колёс и дополнительных условий.</p></div><div><span>03</span><p><strong>История работ</strong><br>Пример карточки показывает несколько работ за одно посещение.</p></div></div></div></section>`}
const faq=[['Что входит в шиномонтаж?','Состав зависит от комплекта и задачи. При выборе филиала уточните монтаж, балансировку и дополнительные работы.'],['Сколько занимает работа?','Время зависит от автомобиля, колёс и загрузки филиала. Доступное время показывается при записи.'],['Работаете с RunFlat?','Для RunFlat могут потребоваться отдельные условия. Уточните модель шин и филиал до записи.'],['Можно отремонтировать шину?','Возможность ремонта определяют после осмотра повреждения. Можно заранее описать проблему в обращении.'],['Есть сезонное хранение?','Условия хранения зависят от филиала и подтверждаются отдельно.'],['Как записаться?','Нажмите «Записаться», выберите город и филиал, затем доступное время в едином Booking.']];
function faqSection(){return `<section class="next-section next-container faq-section" aria-labelledby="faq-title">${heading('КОРОТКО О ГЛАВНОМ','Частые вопросы',null,'faq-title')}<div class="faq-list">${faq.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`}
function branchCard(b){return `<article class="branch-card"><span class="branch-mark">К</span><div class="eyebrow">${b.city.toUpperCase()}${b.real?'':' · DEMO / FUTURE NETWORK STATE'}</div><h3>${b.name}</h3><p>${b.city}, ${b.address}</p><div class="branch-divider"></div><dl><div><dt>Режим работы</dt><dd>Уточняется для филиала</dd></div></dl><div class="branch-actions"><button type="button" class="button secondary" data-action="route" data-id="${b.id}">Маршрут ${arrow}</button><button type="button" class="button primary" data-action="booking" data-id="${b.id}">Выбрать для записи</button></div></article>`}
function locations(){const byCity={};for(const b of branches())(byCity[b.city]??=[]).push(b);return `<section id="locations" class="next-section next-container" aria-labelledby="locations-title">${heading('ГЕОГРАФИЯ СЕРВИСА',isCity()?'Филиалы в Подольске':'Где доступен шиномонтаж',isCity()?'Выберите место обслуживания и уточните условия записи.':'Доступность и стоимость относятся к конкретному филиалу.','locations-title')}${future()?'<p class="future-banner">DEMO / FUTURE NETWORK STATE · Дополнительные города и филиалы синтетические.</p>':''}<div class="locations-layout"><div class="city-groups">${Object.entries(byCity).map(([city,list])=>`<div class="city-group"><div class="city-heading"><h3>${city}</h3><span>${list.length} ${list.length===1?'филиал':'филиала'}</span></div><div class="branch-grid">${list.map(branchCard).join('')}</div></div>`).join('')}</div><div class="map-panel" aria-label="Схема местоположения"><div class="map-grid"><span class="map-pin">К</span><span class="map-road road-one"></span><span class="map-road road-two"></span></div><div class="map-caption"><strong>${isCity()?'Подольск':'Выберите филиал'}</strong><small>Место маршрута · автономный прототип</small></div></div></div></section>`}
function calculator(){return `<section class="calculator-slot next-container" aria-label="Место будущего калькулятора"><div class="eyebrow">FUTURE DESIGN PLACEHOLDER</div><strong>Калькулятор стоимости</strong><p>Место в структуре страницы зарезервировано. Расчёт и ввод данных не реализованы.</p></section>`}
function footer(){return `<footer class="next-footer next-container">${brand()}<span>Сервис, которому можно доверить дорогу.</span><button type="button" class="next-footer-login" data-action="booking">Записаться</button><small>© 2026 КОЛЕСОВИК · Локальный дизайн-прототип</small></footer>`}
function render(){document.title=(isCity()?'Шиномонтаж в Подольске':'Шиномонтаж')+' — КОЛЕСОВИК · визуальный прототип';$('#state-select').value=state;$('#technical-status').textContent=insufficient()?'GENERATE_NOINDEX (visual only)':'GENERATE_INDEX (visual only)';const sparse=insufficient()?`<section class="next-section next-container sparse-section" id="works"><div class="eyebrow">ЛОКАЛЬНЫЕ ДАННЫЕ</div><h2>Пока без местных примеров работ</h2><p>Доступный филиал и путь к записи остаются на странице. Локальные работы и точная цена появятся после подтверждения источников.</p><a class="text-link" href="?state=MASTER_CURRENT">О шиномонтаже в сети ${arrow}</a></section>`:'';$('#app').innerHTML=`<div class="next-home">${header()}<main id="content">${breadcrumbs()}${hero()}${facts()}${bookingStrip()}${price()}${sparse||worksSection()}${insufficient()?'':tyresSection()}${related()}${insufficient()?'':proof()}${faqSection()}${locations()}${calculator()}</main>${footer()}</div>`}
function openOverlay(title,body,type='modal'){lastFocus=document.activeElement;$('#overlay-root').innerHTML=`<div class="overlay-backdrop" data-action="backdrop"><section class="overlay-panel ${type}" role="dialog" aria-modal="true" aria-labelledby="overlay-title" tabindex="-1"><div class="overlay-head"><div class="eyebrow">ЛОКАЛЬНЫЙ ВИЗУАЛЬНЫЙ ПРОТОТИП</div><button type="button" data-action="close" aria-label="Закрыть">×</button></div><h2 id="overlay-title">${title}</h2>${body}</section></div>`;document.body.classList.add('overlay-open');$('.overlay-panel').focus()}
function closeOverlay(){if(!$('#overlay-root').innerHTML)return;$('#overlay-root').innerHTML='';document.body.classList.remove('overlay-open');if(lastFocus?.isConnected)lastFocus.focus()}
function booking(id){selectedBranch=branches().find(b=>b.id===id)||null;openOverlay('Запись на шиномонтаж',`<p>Единый Booking · визуальная точка входа. Услуга предвыбрана; запись не создаётся.</p><dl class="context-list"><div><dt>Услуга</dt><dd>Шиномонтаж</dd></div><div><dt>Город</dt><dd>${isCity()?'Подольск':'Выбрать город'}</dd></div><div><dt>Филиал</dt><dd>${selectedBranch?selectedBranch.name:'Выбрать филиал'}</dd></div></dl><p class="overlay-note">Доступность времени и итоговая цена будут проверяться единым Booking для конкретного филиала.</p><button type="button" class="button primary" data-action="close">Вернуться на страницу</button>`,'booking-drawer')}
function ask(){openOverlay('Спросить КОЛЕСОВИК',`<p>Единый вход в Ask с контекстом страницы.</p><dl class="context-list"><div><dt>Вопрос об услуге</dt><dd>Шиномонтаж</dd></div><div><dt>Город</dt><dd>${isCity()?'Подольск':'Не выбран'}</dd></div></dl><p class="overlay-note">Сообщение в этом макете не отправляется.</p><button type="button" class="button primary" data-action="close">Понятно</button>`,'booking-drawer')}
function showWork(id){const w=works.find(x=>x.id===id);if(!w)return;openOverlay('Выполненные работы',`<div class="eyebrow">DEMO · СИНТЕТИЧЕСКИЙ ПРИМЕР</div><h3>${w.car} · ${w.year}</h3><time datetime="${w.iso}">${w.date}</time><ul class="detail-lines">${w.items.map(x=>`<li><span>${x[0]}</span><b>${money(x[1])}</b></li>`).join('')}</ul><div class="detail-total"><span>Итого за работы</span><strong>${money(w.total)}</strong></div><div class="overlay-actions"><button type="button" class="button secondary" data-action="ask">Спросить</button><button type="button" class="button primary" data-action="booking">Записаться</button></div>`)}
function route(id){const b=branches().find(x=>x.id===id);if(!b)return;openOverlay('Маршрут к филиалу',`<h3>${b.name}</h3><p>${b.city}, ${b.address}</p><p class="overlay-note">${b.real?'Адрес действующего филиала. В автономном макете внешняя карта не открывается.':'DEMO / FUTURE NETWORK STATE · Адрес синтетический, реального маршрута нет.'}</p><button type="button" class="button primary" data-action="close">Закрыть</button>`)}
function tyreDetail(id){const t=tyres.find(x=>x.model===id);if(!t)return;openOverlay(`${t.brand} ${t.model}`,`<p>${t.size} · ${t.season}</p><p><strong>${money(t.price)} / шт. · DEMO PRICE</strong></p><p class="overlay-note">Товар и цена вымышлены. Наличие в городе и филиале не подтверждено.</p><button type="button" class="button primary" data-action="close">Закрыть</button>`)}
function controls(open){$('#prototype-controls').hidden=!open;$('#controls-open').setAttribute('aria-expanded',String(open));if(open){lastFocus=document.activeElement;$('.controls-panel').focus()}else if(lastFocus?.isConnected)lastFocus.focus()}
document.addEventListener('click',e=>{if(e.target.classList?.contains('overlay-backdrop')){closeOverlay();return}const t=e.target.closest('button,a');if(!t)return;if(t.dataset.season){season=t.dataset.season;const y=scrollY;render();scrollTo(0,y);return}const action=t.dataset.action;if(!action)return;if(action==='menu'){const nav=$('#site-nav');nav.classList.toggle('open');t.setAttribute('aria-expanded',String(nav.classList.contains('open')));return}if(action==='close'){closeOverlay();return}if(action==='booking'){closeOverlay();booking(t.dataset.id);return}if(action==='ask'){closeOverlay();ask();return}if(action==='work'){showWork(t.dataset.id);return}if(action==='route'){route(t.dataset.id);return}if(action==='tyre'){tyreDetail(t.dataset.id);return}if(action==='all-tyres'){e.preventDefault();openOverlay('Все шины',`<p>Будущий переход в каталог. В автономном прототипе доступна только демонстрационная подборка.</p><button type="button" class="button primary" data-action="close">Закрыть</button>`);return}if(action==='full-price'){openOverlay('Полный прайс',`<p>Будущий переход к полному прайсу выбранного филиала. Проверенного источника цен для этого статического макета нет.</p><button type="button" class="button primary" data-action="close">Закрыть</button>`);return}});
$('#controls-open').addEventListener('click',()=>controls(true));$('#controls-close').addEventListener('click',()=>controls(false));$('#controls-hide').addEventListener('click',()=>controls(false));$('#state-select').addEventListener('change',e=>{state=e.target.value;season='Популярные';history.replaceState(null,'',location.pathname+'?state='+state);render();controls(false);scrollTo(0,0)});
const readTheme=()=>{try{return localStorage.getItem('shin-prototype-theme')||'light'}catch{return 'light'}};
function applyTheme(value){document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value}
$('#theme-select').value=readTheme();$('#theme-select').addEventListener('change',e=>{try{localStorage.setItem('shin-prototype-theme',e.target.value)}catch{}applyTheme(e.target.value)});matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(readTheme()==='system')applyTheme('system')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#prototype-controls').hidden)controls(false);else closeOverlay()}if(e.key==='p'&&e.altKey&&e.shiftKey)controls($('#prototype-controls').hidden);if(e.key==='Tab'){const panel=!$('#prototype-controls').hidden?$('.controls-panel'):$('.overlay-panel');if(!panel)return;const items=[...panel.querySelectorAll('button,select,a')].filter(x=>!x.disabled);if(!items.length)return;if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0].focus()}}});
render();
