/* Autonomous maintenance design prototype. No fetch, product API, form submission or external assets. */
const $=(selector,root=document)=>root.querySelector(selector);
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14M13 5l7 7-7 7"/></svg>';
const carIcon='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m4 11 2-5h12l2 5M3 11h18v8H3zM6 19v2m12-2v2M6 15h.01M18 15h.01"/></svg>';
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const states=['NO_VEHICLE','VEHICLE_SELECTED','KNOWN_CUSTOMER_CAR'];
let state=states.includes(new URLSearchParams(location.search).get('state'))?new URLSearchParams(location.search).get('state'):'NO_VEHICLE';
const models={Volkswagen:['Polo','Golf'],Kia:['Rio','Ceed'],Toyota:['Corolla','Camry']};
const demoVehicle={make:'Volkswagen',model:'Polo',year:'2020',engine:'1.6',mileage:67400};
const knownVehicle={make:'Kia',model:'Rio',year:'2021',engine:'1.6',mileage:58100};
let vehicle=state==='KNOWN_CUSTOMER_CAR'?{...knownVehicle}:state==='VEHICLE_SELECTED'?{...demoVehicle}:null;
let lastFocus=null;
const visits=[
 {id:'polo',car:'Volkswagen Polo',year:'2020',date:'16 сентября 2026',iso:'2026-09-16',items:[['Замена моторного масла',1700],['Масляный фильтр · материал',900],['Проверка тормозной системы',700]],total:3300},
 {id:'rio',car:'Kia Rio',year:'2021',date:'9 сентября 2026',iso:'2026-09-09',items:[['Замена масла',1700],['Масляный фильтр · материал',850],['Воздушный фильтр · материал',1100],['Осмотр ходовой',800]],total:4450}
];
const maintenance=[
 ['ЗАМЕНИТЬ СЕЙЧАС','replace',[['Моторное масло','DEMO: пример строки обслуживания'],['Масляный фильтр','DEMO: пример расходника'],['Воздушный фильтр','DEMO: пример регламентной позиции']]],
 ['ПРОВЕРИТЬ','inspect',[['Тормозная система','DEMO: оценка состояния'],['Ходовая и шины','DEMO: осмотр'],['Уровни жидкостей','DEMO: проверка']]],
 ['ПО РЕГЛАМЕНТУ / СРОКУ','later',[['Салонный фильтр','DEMO: срок нужно подтвердить'],['Тормозная жидкость','DEMO: срок нужно подтвердить']]]
];
const products=[
 {id:'oil',kind:'Моторное масло',name:'DEMO PRODUCT · масло',spec:'Допуск, вязкость и объём — после проверки',basis:'Моторное масло'},
 {id:'filter',kind:'Масляный фильтр',name:'DEMO PRODUCT · фильтр',spec:'Артикул — после проверки варианта двигателя',basis:'Масляный фильтр'},
 {id:'air',kind:'Воздушный фильтр',name:'DEMO PRODUCT · фильтр',spec:'Размер и применимость — после проверки',basis:'Воздушный фильтр'}
];
const faq=[
 ['Что такое плановое ТО?','Обслуживание по применимому регламенту и состоянию автомобиля. Состав зависит от модели, пробега, возраста и известной истории.'],
 ['Почему состав ТО отличается у автомобилей?','У разных вариантов автомобиля отличаются операции и сроки. Их нужно сверить по надёжному источнику для конкретной машины.'],
 ['Зачем указывать пробег?','Он помогает определить, какие регламентные позиции пора рассмотреть. Если история неполная, состав уточняется при записи.'],
 ['Почему здесь нет точной цены?','Работы и материалы зависят от автомобиля и согласованного состава. В прототипе действующий расчёт не подключён.'],
 ['Что если при осмотре обнаружена неисправность?','Её фиксируют рекомендацией. Дополнительный ремонт обсуждается и согласуется отдельно от планового ТО.'],
 ['Как записаться?','Кнопка «Записаться» в этом прототипе показывает будущий вход в действующий Booking. Запись здесь не создаётся.']
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function brand(){return '<a class="brand" href="#top" aria-label="КОЛЕСОВИК — к началу страницы"><span class="brand-symbol">К</span><span>КОЛЕСОВИК</span></a>'}
function header(){return '<header id="top" class="next-header next-container">'+brand()+'<nav id="site-nav" class="next-nav" aria-label="Главная навигация"><a href="#vehicle-picker">Подобрать ТО</a><a href="#included">Состав</a><a href="#materials">Материалы</a><a href="#works">Работы</a><a href="#locations">Адрес</a></nav><div class="next-header-actions"><button type="button" class="next-account" data-action="booking">Запись '+arrow+'</button><button type="button" class="next-menu" data-action="menu" aria-label="Открыть меню" aria-expanded="false" aria-controls="site-nav"><span></span><span></span></button></div></header>'}
function breadcrumbs(){return '<nav class="breadcrumbs next-container" aria-label="Путь"><a href="#top">Главная</a><span> / </span><span>Услуги</span><span> / </span><span aria-current="page">Плановое ТО</span></nav>'}
function heading(kicker,title,description,id){return '<div class="next-section-heading"><div><div class="eyebrow">'+kicker+'</div><h2 id="'+id+'">'+title+'</h2>'+(description?'<p>'+description+'</p>':'')+'</div></div>'}
function hero(){return '<section class="service-hero next-container" aria-labelledby="page-title"><div class="hero-copy"><div class="eyebrow"><span class="next-eyebrow-line"></span>КОЛЕСОВИК · АВТОСЕРВИС</div><h1 id="page-title">Плановое <em>ТО</em></h1><p class="hero-lead">Подберём обслуживание под ваш автомобиль и пробег. Покажем, что нужно заменить, что проверить и что можно оставить до следующего ТО.</p><div class="next-hero-buttons"><button type="button" class="button primary large" data-action="picker">Подобрать ТО '+arrow+'</button><button type="button" class="button secondary large" data-action="ask">Спросить</button></div><p class="next-assurance"><span>✓</span><span>Подольск · Станционная, 11/1</span></p></div><div class="hero-visual"><picture><source media="(max-width:767px)" srcset="assets/service-mobile.webp"><img src="assets/service.webp" alt="Автомобиль на посту сервиса КОЛЕСОВИК" width="1448" height="1086"></picture><div class="photo-caption"><span class="caption-pin">⌖</span><span><strong>Плановое ТО</strong><small>Подольск · Станционная, 11/1</small></span><span>↗</span></div></div><div class="hero-bottom"><span>АВТОМОБИЛЬ · ПРОБЕГ · СОСТАВ РАБОТ</span><span>ПОДОЛЬСК · СТАНЦИОННАЯ, 11/1</span></div></section>'}
function options(values,selected,placeholder){return '<option value="">'+placeholder+'</option>'+values.map(x=>'<option value="'+esc(x)+'"'+(selected===x?' selected':'')+'>'+esc(x)+'</option>').join('')}
function picker(){const v=vehicle||{make:'',model:'',year:'',engine:'',mileage:''};const available=models[v.make]||[];return '<section id="vehicle-picker" class="next-section next-container" aria-labelledby="picker-title">'+heading('ВАШ АВТОМОБИЛЬ','Что нужно вашему автомобилю','Укажите машину и пробег. Здесь показан пример будущего подбора; актуальный каталог регламентов ещё наполняется.','picker-title')+(state==='KNOWN_CUSTOMER_CAR'?'<div class="customer-context"><span class="eyebrow">DEMO · ИЗ ЛИЧНОГО КАБИНЕТА</span><p>Синтетический пример: автомобиль и последний известный пробег уже переданы в форму. Перед записью данные можно уточнить.</p></div>':'')+'<form id="vehicle-form" class="vehicle-form"><label>Марка<select id="vehicle-make" name="make" required>'+options(Object.keys(models),v.make,'Выберите марку')+'</select></label><label>Модель<select id="vehicle-model" name="model" required'+(v.make?'':' disabled')+'>'+options(available,v.model,'Выберите модель')+'</select></label><label>Год<select name="year" required>'+options(['2018','2019','2020','2021','2022','2023'],v.year,'Выберите год')+'</select></label><label>Двигатель<select name="engine" required>'+options(['1.4','1.6','2.0'],v.engine,'Уточните двигатель')+'</select></label><label class="mileage-field">Текущий пробег<input name="mileage" type="number" inputmode="numeric" min="0" max="999999" step="1" placeholder="Например, 67 400" value="'+esc(v.mileage)+'" required><span>км</span></label><div class="vehicle-submit"><button type="submit" class="button primary large">Показать состав '+arrow+'</button><small>Пример подбора не является заводским регламентом.</small></div></form></section>'}
function result(){if(!vehicle)return '<section id="maintenance-result" class="next-section next-container result-empty" aria-labelledby="result-title">'+heading('ПОСЛЕ ВЫБОРА','Состав ТО появится здесь','Сначала укажите автомобиль и пробег. Дальше покажем структуру плановых работ, проверок и материалов.','result-title')+'<div class="empty-rule">Никакие позиции не назначены без автомобиля.</div></section>';const name=esc(vehicle.make+' '+vehicle.model);return '<section id="maintenance-result" class="next-section next-container" aria-labelledby="result-title">'+heading('DEMO COMPOSITION · НЕ ЗАВОДСКОЙ РЕГЛАМЕНТ','Пример состава ТО','Позиции ниже показывают устройство будущего результата и не относятся к выбранной модели без проверенного источника.','result-title')+'<div class="selected-vehicle"><span>'+carIcon+'</span><div><strong>'+name+'</strong><small>'+esc(vehicle.year)+' · '+esc(vehicle.engine)+' · '+money(vehicle.mileage).replace(' ₽',' км')+'</small></div><span class="vehicle-demo">DEMO</span></div><div class="maintenance-grid">'+maintenance.map(group=>'<article class="maintenance-column '+group[1]+'"><div class="maintenance-head"><span class="eyebrow">'+group[0]+'</span><small>DEMO</small></div><ul>'+group[2].map(item=>'<li><strong>'+item[0]+'</strong><span>'+item[1]+'</span></li>').join('')+'</ul></article>').join('')+'</div><p class="result-disclaimer">Реальные сроки, операции и история обслуживания потребуют проверки собственного Maintenance Catalog КОЛЕСОВИКа.</p></section>'}
function included(){return '<section id="included" class="next-section next-container" aria-labelledby="included-title">'+heading('ОБЩИЙ ОРИЕНТИР','Что обычно проверяем при ТО','Это направления осмотра, а не одинаковый заводской список замен для каждого автомобиля.','included-title')+'<div class="check-grid">'+[['Масло и фильтр','Проверяем, какие операции подошли по регламенту и истории.'],['Жидкости','Оцениваем уровни и состояние там, где это предусмотрено.'],['Тормоза и ходовая','Осматриваем состояние и фиксируем замечания.'],['Рулевое и шины','Проверяем доступные узлы, износ и повреждения.'],['Доступные узлы','Обращаем внимание на течи и повреждения.'],['Сервисный интервал','Уточняем и обновляем, когда это применимо к автомобилю.']].map((x,i)=>'<div class="check-item"><span>0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></div>').join('')+'</div></section>'}
function variableRules(){return '<section class="next-section next-container" aria-labelledby="rules-title">'+heading('ЗАВИСИТ ОТ МОДЕЛИ И СРОКА','Позиции по регламенту','Они могут потребоваться по пробегу или возрасту. Это не список замен на каждом ТО.','rules-title')+'<div class="rule-strip"><p>Фильтры · свечи · тормозная и охлаждающая жидкости · масло трансмиссии, раздатки или редуктора · ремни и другие позиции.</p><span>Срок для конкретного автомобиля нужно подтвердить.</span></div></section>'}
function noExtras(){return '<section class="next-trust" aria-labelledby="trust-title"><div class="next-container trust-content"><div class="trust-intro"><div class="eyebrow">ПРИНЦИП ОБСЛУЖИВАНИЯ</div><h2 id="trust-title">Без лишних<br><em>замен.</em></h2><p>Состав зависит от автомобиля, пробега, возраста и известной истории обслуживания. То, что ещё не подошло по сроку, не добавляем автоматически.</p></div><div class="trust-principles"><div><span>01</span><p><strong>Плановые позиции</strong><br>Основание — применимый регламент и история машины.</p></div><div><span>02</span><p><strong>Находки при осмотре</strong><br>Неисправности фиксируем отдельно от планового ТО.</p></div><div><span>03</span><p><strong>Дальнейшие работы</strong><br>Рекомендацию объясняем и отдельно согласуем ремонт.</p></div></div></div></section>'}
function materials(){return '<section id="materials" class="next-section next-container" aria-labelledby="materials-title">'+heading('FUTURE PRODUCT CONTRACT','Материалы для вашего ТО',vehicle?'DEMO: карточки следуют из показанных выше операций. Применимость к автомобилю пока не проверена.':'После выбора автомобиля и состава ТО здесь появятся материалы в контексте нужных операций.','materials-title')+(vehicle?'<p class="material-context">Контекст подбора: <strong>'+esc(vehicle.make+' '+vehicle.model)+' · '+new Intl.NumberFormat('ru-RU').format(vehicle.mileage)+' км</strong> · DEMO, не подтверждение совместимости.</p><div class="next-products-grid">'+products.map((p,i)=>'<article class="next-product-card maintenance-product"><div class="next-product-media"><span>0'+(i+1)+' · DEMO</span><div class="material-glyph" aria-hidden="true">'+['◫','▤','▥'][i]+'</div></div><div class="next-product-brand">'+p.kind+'</div><div class="next-product-identity"><h3>'+p.name+'</h3><p class="next-product-size">'+p.spec+'</p></div><p class="product-basis">Основание: '+p.basis+'</p><p class="product-status">Подбор для прототипа · совместимость не подтверждена</p><button type="button" class="next-product-buy" data-action="product" data-id="'+p.id+'">Подробнее '+arrow+'</button></article>').join('')+'</div>':'<div class="empty-rule">Нет предложений без автомобиля и состава ТО.</div>')+'</section>'}
function cost(){return '<section id="cost" class="next-section next-container" aria-labelledby="cost-title">'+heading('FUTURE CALCULATION','Из чего сложится стоимость','Итог появится после проверки состава работ, материалов и актуальных цен.','cost-title')+'<div class="cost-panel"><div><span>Работы</span><strong>После подбора</strong></div><div><span>Материалы</span><strong>После подбора</strong></div><div><span>Регламентные позиции</span><strong>После проверки</strong></div><div class="cost-total"><span>Итого</span><strong>Пока не рассчитано</strong></div></div><p class="cost-note">В прототипе нет действующей цены или предложения.</p></section>'}
function bookingStrip(){return '<section id="booking" class="booking-strip next-container" aria-label="Запись на плановое ТО"><div><div class="eyebrow">СЛЕДУЮЩИЙ ШАГ</div><h2>Запишитесь на плановое ТО</h2><p>Автомобиль и пробег помогут обсудить состав работ при записи.</p></div><button type="button" class="button primary large" data-action="booking">Записаться '+arrow+'</button></section>'}
function process(){return '<section id="process" class="next-section next-container" aria-labelledby="process-title">'+heading('ПО ПОРЯДКУ','Как проходит ТО',null,'process-title')+'<ol class="process-list">'+[['Уточняем автомобиль','Сверяем модель, вариант, пробег и историю.'],['Определяем состав','Выделяем плановые замены и проверки.'],['Выполняем согласованное','Работы и материалы остаются в одном посещении.'],['Фиксируем результат','Отмечаем сделанное и отдельные рекомендации.']].map((x,i)=>'<li><span class="process-index">0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></li>').join('')+'</ol></section>'}
function workCard(w){return '<article class="next-work-card"><div class="next-work-header"><span>'+carIcon+'</span><time datetime="'+w.iso+'">'+w.date+'</time></div><div class="next-work-identity"><h3>'+w.car+'</h3><p>'+w.year+' год · Подольск · DEMO</p></div><ul class="next-work-summary">'+w.items.map(x=>'<li><span>'+x[0]+'</span><b>'+money(x[1])+'</b></li>').join('')+'</ul><div class="next-work-footer"><div><small>Итого за работы и материалы · DEMO</small><strong>'+money(w.total)+'</strong></div><button type="button" class="next-work-view" data-action="work" data-id="'+w.id+'">Смотреть '+arrow+'</button></div></article>'}
function works(){return '<section id="works" class="next-section next-container" aria-labelledby="works-title">'+heading('ОДИН АВТОМОБИЛЬ · НЕСКОЛЬКО ПОЗИЦИЙ','Выполненные работы','Синтетические примеры карточки посещения. Не реальные заказы, регламент или действующий прайс.','works-title')+'<div class="next-works-grid" aria-label="Синтетические примеры посещений">'+visits.map(workCard).join('')+'</div></section>'}
function historyBlock(){return '<section id="history" class="next-section next-container" aria-labelledby="history-title">'+heading('FUTURE CUSTOMER EXPERIENCE','Всё остаётся в истории автомобиля','В будущем данные визита и документы будут связаны с конкретной машиной и заказом.','history-title')+'<div class="history-list">'+[['Пробег и дата','Основа хронологии обслуживания.'],['Работы и материалы','Что выполнено и что установлено.'],['Рекомендации','Что стоит сделать отдельно или позже.'],['Следующее обслуживание','Ориентир после подтверждения регламента.'],['Документы','Акт заказа сейчас; отчёты оборудования и чек-лист ТО — future.']].map((x,i)=>'<div><span>0'+(i+1)+'</span><strong>'+x[0]+'</strong><p>'+x[1]+'</p></div>').join('')+'</div><p class="history-note">PDF сход-развала, отчёт компьютерной диагностики и документ ТО потребуют отдельной интеграции; экспорт оборудования ещё не проверен.</p></section>'}
function faqBlock(){return '<section class="next-section next-container faq-section" aria-labelledby="faq-title">'+heading('КОРОТКО О ГЛАВНОМ','Частые вопросы',null,'faq-title')+'<div class="faq-list">'+faq.map(x=>'<details><summary>'+x[0]+'<span aria-hidden="true">+</span></summary><p>'+x[1]+'</p></details>').join('')+'</div></section>'}
function locationBlock(){return '<section id="locations" class="next-section next-container" aria-labelledby="locations-title">'+heading('АДРЕС СЕРВИСА','Где пройти ТО','Подольск · Станционная, 11/1. Маршрут и запись — ниже.','locations-title')+'<div class="locations-layout"><div class="city-groups"><div class="city-group"><div class="city-heading"><h3>Подольск</h3><span>1 адрес</span></div><div class="branch-grid"><article class="branch-card"><span class="branch-mark">К</span><div class="eyebrow">ПОДОЛЬСК</div><h3>КОЛЕСОВИК · Станционная</h3><p>Подольск, Станционная, 11/1</p><div class="branch-divider"></div><dl><div><dt>Режим работы</dt><dd>Уточните перед визитом</dd></div></dl><div class="branch-actions"><button type="button" class="button secondary" data-action="route">Маршрут '+arrow+'</button><button type="button" class="button primary" data-action="booking">Записаться</button></div></article></div></div></div><div class="map-panel" aria-label="Схема местоположения"><div class="map-grid"><span class="map-pin">К</span><span class="map-road road-one"></span><span class="map-road road-two"></span></div><div class="map-caption"><strong>Подольск</strong><small>Станционная, 11/1 · схема для прототипа</small></div></div></div></section>'}
function footer(){return '<footer class="next-footer next-container">'+brand()+'<span>Сервис, которому можно доверить дорогу.</span><button type="button" class="next-footer-login" data-action="booking">Записаться</button><small>© 2026 КОЛЕСОВИК · Дизайн-прототип</small></footer>'}
function render(){document.title='Плановое ТО — КОЛЕСОВИК · визуальный прототип';$('#state-select').value=state;$('#technical-key').textContent=state;$('#app').innerHTML='<div class="next-home">'+header()+'<main id="content">'+breadcrumbs()+hero()+picker()+result()+included()+variableRules()+noExtras()+materials()+cost()+bookingStrip()+process()+works()+historyBlock()+faqBlock()+locationBlock()+'</main>'+footer()+'</div>'}
function openOverlay(title,body,type='modal'){lastFocus=document.activeElement;$('#overlay-root').innerHTML='<div class="overlay-backdrop" data-action="backdrop"><section class="overlay-panel '+type+'" role="dialog" aria-modal="true" aria-labelledby="overlay-title" tabindex="-1"><div class="overlay-head"><div class="eyebrow">КОЛЕСОВИК · ПЛАНОВОЕ ТО</div><button type="button" data-action="close" aria-label="Закрыть">×</button></div><h2 id="overlay-title">'+title+'</h2>'+body+'</section></div>';document.body.classList.add('overlay-open');$('.overlay-panel').focus()}
function closeOverlay(){if(!$('#overlay-root').innerHTML)return;$('#overlay-root').innerHTML='';document.body.classList.remove('overlay-open');if(lastFocus&&lastFocus.isConnected)lastFocus.focus()}
function booking(){const context=vehicle?'<div><dt>Автомобиль · DEMO</dt><dd>'+esc(vehicle.make+' '+vehicle.model)+'</dd></div><div><dt>Пробег · DEMO</dt><dd>'+new Intl.NumberFormat('ru-RU').format(vehicle.mileage)+' км</dd></div>':'';openOverlay('Запись на плановое ТО','<p>На рабочем сайте здесь откроется выбор даты и времени.</p><dl class="context-list"><div><dt>Услуга</dt><dd>Плановое ТО</dd></div>'+context+'<div><dt>Адрес</dt><dd>Подольск · Станционная, 11/1</dd></div></dl><p class="overlay-note">В этом макете запись не создаётся. Состав работ уточняется при записи.</p><button type="button" class="button primary" data-action="close">Вернуться на страницу</button>','booking-drawer')}
function ask(){openOverlay('Спросить','<p>На рабочем сайте здесь откроется диалог с сервисом.</p><p class="overlay-note">В этом макете сообщение не отправляется.</p><button type="button" class="button primary" data-action="close">Понятно</button>','booking-drawer')}
function showWork(id){const w=visits.find(x=>x.id===id);if(!w)return;openOverlay('Выполненные работы','<div class="eyebrow">DEMO · СИНТЕТИЧЕСКИЙ ПРИМЕР</div><h3>'+w.car+' · '+w.year+'</h3><time datetime="'+w.iso+'">'+w.date+'</time><ul class="detail-lines">'+w.items.map(x=>'<li><span>'+x[0]+'</span><b>'+money(x[1])+'</b></li>').join('')+'</ul><div class="detail-total"><span>Итого за визит · DEMO</span><strong>'+money(w.total)+'</strong></div><div class="overlay-actions"><button type="button" class="button secondary" data-action="ask">Спросить</button><button type="button" class="button primary" data-action="booking">Записаться</button></div>')}
function showProduct(id){const p=products.find(x=>x.id===id);if(!p)return;openOverlay(p.kind,'<div class="eyebrow">DEMO PRODUCT · FUTURE CONTRACT</div><h3>'+p.name+'</h3><p>'+p.spec+'</p><p class="overlay-note">Карточка связана с примером операции «'+p.basis+'». Совместимость, объём и цена не подтверждены; корзины в прототипе нет.</p><button type="button" class="button primary" data-action="close">Вернуться на страницу</button>')}
function route(){openOverlay('Маршрут к сервису','<h3>КОЛЕСОВИК · Станционная</h3><p>Подольск, Станционная, 11/1</p><p class="overlay-note">Адрес действующего сервиса. В этом макете внешняя карта не открывается.</p><button type="button" class="button primary" data-action="close">Закрыть</button>')}
function controls(open){$('#prototype-controls').hidden=!open;$('#controls-open').setAttribute('aria-expanded',String(open));if(open){lastFocus=document.activeElement;$('.controls-panel').focus()}else if(lastFocus&&lastFocus.isConnected)lastFocus.focus()}
document.addEventListener('submit',e=>{if(e.target.id!=='vehicle-form')return;e.preventDefault();const data=new FormData(e.target);const make=String(data.get('make')||''),model=String(data.get('model')||''),year=String(data.get('year')||''),engine=String(data.get('engine')||''),mileage=Number(data.get('mileage'));if(!models[make]?.includes(model)||!['2018','2019','2020','2021','2022','2023'].includes(year)||!['1.4','1.6','2.0'].includes(engine)||!Number.isInteger(mileage)||mileage<0||mileage>999999)return;vehicle={make,model,year,engine,mileage};state='VEHICLE_SELECTED';history.replaceState(null,'','?state=VEHICLE_SELECTED');render();requestAnimationFrame(()=>$('#maintenance-result').scrollIntoView({block:'start',behavior:'smooth'}))});
document.addEventListener('change',e=>{if(e.target.id==='vehicle-make'){const model=$('#vehicle-model');model.innerHTML=options(models[e.target.value]||[],'','Выберите модель');model.disabled=!e.target.value}});
document.addEventListener('click',e=>{if(e.target.classList?.contains('overlay-backdrop')){closeOverlay();return}const t=e.target.closest('button');if(!t)return;const action=t.dataset.action;if(action==='menu'){const nav=$('#site-nav');nav.classList.toggle('open');t.setAttribute('aria-expanded',String(nav.classList.contains('open')));return}if(action==='picker'){$('#vehicle-picker').scrollIntoView({block:'start',behavior:'smooth'});$('#vehicle-make').focus({preventScroll:true});return}if(action==='close'){closeOverlay();return}if(action==='booking'){closeOverlay();booking();return}if(action==='ask'){closeOverlay();ask();return}if(action==='work'){showWork(t.dataset.id);return}if(action==='product'){showProduct(t.dataset.id);return}if(action==='route'){route()}});
$('#controls-open').addEventListener('click',()=>controls(true));$('#controls-close').addEventListener('click',()=>controls(false));$('#controls-hide').addEventListener('click',()=>controls(false));
$('#state-select').addEventListener('change',e=>{state=e.target.value;vehicle=state==='KNOWN_CUSTOMER_CAR'?{...knownVehicle}:state==='VEHICLE_SELECTED'?{...demoVehicle}:null;history.replaceState(null,'','?state='+state);controls(false);render()});
$('#theme-select').addEventListener('change',e=>{const t=e.target.value;try{localStorage.setItem('maintenance-prototype-theme',t)}catch{}document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeOverlay();controls(false)}});
render();
